// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ast.proto

package ast

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DirectiveLocation_Loc int32

const (
	DirectiveLocation_NoPos DirectiveLocation_Loc = 0
	// ExecutableDirectiveLocations
	DirectiveLocation_QUERY               DirectiveLocation_Loc = 1
	DirectiveLocation_MUTATION            DirectiveLocation_Loc = 2
	DirectiveLocation_SUBSCRIPTION        DirectiveLocation_Loc = 3
	DirectiveLocation_FIELD               DirectiveLocation_Loc = 4
	DirectiveLocation_FRAGMENT_DEFINITION DirectiveLocation_Loc = 5
	DirectiveLocation_FRAGMENT_SPREAD     DirectiveLocation_Loc = 6
	DirectiveLocation_INLINE_FRAGMENT     DirectiveLocation_Loc = 7
	DirectiveLocation_VARIABLE_DEFINITION DirectiveLocation_Loc = 8
	// TypeSystemDirectiveLocations
	DirectiveLocation_DOCUMENT               DirectiveLocation_Loc = 9
	DirectiveLocation_SCHEMA                 DirectiveLocation_Loc = 10
	DirectiveLocation_SCALAR                 DirectiveLocation_Loc = 11
	DirectiveLocation_OBJECT                 DirectiveLocation_Loc = 12
	DirectiveLocation_FIELD_DEFINITION       DirectiveLocation_Loc = 13
	DirectiveLocation_ARGUMENT_DEFINITION    DirectiveLocation_Loc = 14
	DirectiveLocation_INTERFACE              DirectiveLocation_Loc = 15
	DirectiveLocation_UNION                  DirectiveLocation_Loc = 16
	DirectiveLocation_ENUM                   DirectiveLocation_Loc = 17
	DirectiveLocation_ENUM_VALUE             DirectiveLocation_Loc = 18
	DirectiveLocation_INPUT_OBJECT           DirectiveLocation_Loc = 19
	DirectiveLocation_INPUT_FIELD_DEFINITION DirectiveLocation_Loc = 20
)

var DirectiveLocation_Loc_name = map[int32]string{
	0:  "NoPos",
	1:  "QUERY",
	2:  "MUTATION",
	3:  "SUBSCRIPTION",
	4:  "FIELD",
	5:  "FRAGMENT_DEFINITION",
	6:  "FRAGMENT_SPREAD",
	7:  "INLINE_FRAGMENT",
	8:  "VARIABLE_DEFINITION",
	9:  "DOCUMENT",
	10: "SCHEMA",
	11: "SCALAR",
	12: "OBJECT",
	13: "FIELD_DEFINITION",
	14: "ARGUMENT_DEFINITION",
	15: "INTERFACE",
	16: "UNION",
	17: "ENUM",
	18: "ENUM_VALUE",
	19: "INPUT_OBJECT",
	20: "INPUT_FIELD_DEFINITION",
}

var DirectiveLocation_Loc_value = map[string]int32{
	"NoPos":                  0,
	"QUERY":                  1,
	"MUTATION":               2,
	"SUBSCRIPTION":           3,
	"FIELD":                  4,
	"FRAGMENT_DEFINITION":    5,
	"FRAGMENT_SPREAD":        6,
	"INLINE_FRAGMENT":        7,
	"VARIABLE_DEFINITION":    8,
	"DOCUMENT":               9,
	"SCHEMA":                 10,
	"SCALAR":                 11,
	"OBJECT":                 12,
	"FIELD_DEFINITION":       13,
	"ARGUMENT_DEFINITION":    14,
	"INTERFACE":              15,
	"UNION":                  16,
	"ENUM":                   17,
	"ENUM_VALUE":             18,
	"INPUT_OBJECT":           19,
	"INPUT_FIELD_DEFINITION": 20,
}

func (x DirectiveLocation_Loc) String() string {
	return proto.EnumName(DirectiveLocation_Loc_name, int32(x))
}

func (DirectiveLocation_Loc) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_37b5b141da493253, []int{15, 0}
}

// Describes a complete GraphQL Document.
type Document struct {
	// file name, relative to root of source tree.
	Name string    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Doc  *DocGroup `protobuf:"bytes,2,opt,name=doc,proto3" json:"doc,omitempty"`
	// All top-level directives.
	Directives []*DirectiveLit `protobuf:"bytes,3,rep,name=directives,proto3" json:"directives,omitempty"`
	// All top-level definitions in this file.
	Schema               *TypeDecl   `protobuf:"bytes,4,opt,name=schema,proto3" json:"schema,omitempty"`
	Types                []*TypeDecl `protobuf:"bytes,5,rep,name=types,proto3" json:"types,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Document) Reset()         { *m = Document{} }
func (m *Document) String() string { return proto.CompactTextString(m) }
func (*Document) ProtoMessage()    {}
func (*Document) Descriptor() ([]byte, []int) {
	return fileDescriptor_37b5b141da493253, []int{0}
}

func (m *Document) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Document.Unmarshal(m, b)
}
func (m *Document) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Document.Marshal(b, m, deterministic)
}
func (m *Document) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Document.Merge(m, src)
}
func (m *Document) XXX_Size() int {
	return xxx_messageInfo_Document.Size(m)
}
func (m *Document) XXX_DiscardUnknown() {
	xxx_messageInfo_Document.DiscardUnknown(m)
}

var xxx_messageInfo_Document proto.InternalMessageInfo

func (m *Document) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Document) GetDoc() *DocGroup {
	if m != nil {
		return m.Doc
	}
	return nil
}

func (m *Document) GetDirectives() []*DirectiveLit {
	if m != nil {
		return m.Directives
	}
	return nil
}

func (m *Document) GetSchema() *TypeDecl {
	if m != nil {
		return m.Schema
	}
	return nil
}

func (m *Document) GetTypes() []*TypeDecl {
	if m != nil {
		return m.Types
	}
	return nil
}

// A DocGroup is a collection of documentation: descriptions or comments
type DocGroup struct {
	List                 []*DocGroup_Doc `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *DocGroup) Reset()         { *m = DocGroup{} }
func (m *DocGroup) String() string { return proto.CompactTextString(m) }
func (*DocGroup) ProtoMessage()    {}
func (*DocGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_37b5b141da493253, []int{1}
}

func (m *DocGroup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DocGroup.Unmarshal(m, b)
}
func (m *DocGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DocGroup.Marshal(b, m, deterministic)
}
func (m *DocGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DocGroup.Merge(m, src)
}
func (m *DocGroup) XXX_Size() int {
	return xxx_messageInfo_DocGroup.Size(m)
}
func (m *DocGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_DocGroup.DiscardUnknown(m)
}

var xxx_messageInfo_DocGroup proto.InternalMessageInfo

func (m *DocGroup) GetList() []*DocGroup_Doc {
	if m != nil {
		return m.List
	}
	return nil
}

type DocGroup_Doc struct {
	Text                 string   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Char                 int64    `protobuf:"varint,2,opt,name=char,proto3" json:"char,omitempty"`
	Comment              bool     `protobuf:"varint,3,opt,name=comment,proto3" json:"comment,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DocGroup_Doc) Reset()         { *m = DocGroup_Doc{} }
func (m *DocGroup_Doc) String() string { return proto.CompactTextString(m) }
func (*DocGroup_Doc) ProtoMessage()    {}
func (*DocGroup_Doc) Descriptor() ([]byte, []int) {
	return fileDescriptor_37b5b141da493253, []int{1, 0}
}

func (m *DocGroup_Doc) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DocGroup_Doc.Unmarshal(m, b)
}
func (m *DocGroup_Doc) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DocGroup_Doc.Marshal(b, m, deterministic)
}
func (m *DocGroup_Doc) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DocGroup_Doc.Merge(m, src)
}
func (m *DocGroup_Doc) XXX_Size() int {
	return xxx_messageInfo_DocGroup_Doc.Size(m)
}
func (m *DocGroup_Doc) XXX_DiscardUnknown() {
	xxx_messageInfo_DocGroup_Doc.DiscardUnknown(m)
}

var xxx_messageInfo_DocGroup_Doc proto.InternalMessageInfo

func (m *DocGroup_Doc) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *DocGroup_Doc) GetChar() int64 {
	if m != nil {
		return m.Char
	}
	return 0
}

func (m *DocGroup_Doc) GetComment() bool {
	if m != nil {
		return m.Comment
	}
	return false
}

// A Arg represents an Argument pair in a applied directive.
type Arg struct {
	Name *Ident `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Types that are valid to be assigned to Value:
	//	*Arg_BasicLit
	//	*Arg_CompositeLit
	Value                isArg_Value `protobuf_oneof:"value"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Arg) Reset()         { *m = Arg{} }
func (m *Arg) String() string { return proto.CompactTextString(m) }
func (*Arg) ProtoMessage()    {}
func (*Arg) Descriptor() ([]byte, []int) {
	return fileDescriptor_37b5b141da493253, []int{2}
}

func (m *Arg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Arg.Unmarshal(m, b)
}
func (m *Arg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Arg.Marshal(b, m, deterministic)
}
func (m *Arg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Arg.Merge(m, src)
}
func (m *Arg) XXX_Size() int {
	return xxx_messageInfo_Arg.Size(m)
}
func (m *Arg) XXX_DiscardUnknown() {
	xxx_messageInfo_Arg.DiscardUnknown(m)
}

var xxx_messageInfo_Arg proto.InternalMessageInfo

func (m *Arg) GetName() *Ident {
	if m != nil {
		return m.Name
	}
	return nil
}

type isArg_Value interface {
	isArg_Value()
}

type Arg_BasicLit struct {
	BasicLit *BasicLit `protobuf:"bytes,2,opt,name=basicLit,proto3,oneof"`
}

type Arg_CompositeLit struct {
	CompositeLit *CompositeLit `protobuf:"bytes,3,opt,name=compositeLit,proto3,oneof"`
}

func (*Arg_BasicLit) isArg_Value() {}

func (*Arg_CompositeLit) isArg_Value() {}

func (m *Arg) GetValue() isArg_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Arg) GetBasicLit() *BasicLit {
	if x, ok := m.GetValue().(*Arg_BasicLit); ok {
		return x.BasicLit
	}
	return nil
}

func (m *Arg) GetCompositeLit() *CompositeLit {
	if x, ok := m.GetValue().(*Arg_CompositeLit); ok {
		return x.CompositeLit
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Arg) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Arg_BasicLit)(nil),
		(*Arg_CompositeLit)(nil),
	}
}

// A Field represents a Field declaration in a GraphQL type declaration
// or an argument declaration in an arguments declaration.
//
type Field struct {
	Doc  *DocGroup       `protobuf:"bytes,1,opt,name=doc,proto3" json:"doc,omitempty"`
	Name *Ident          `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Args *InputValueList `protobuf:"bytes,3,opt,name=args,proto3" json:"args,omitempty"`
	// field type
	//
	// Types that are valid to be assigned to Type:
	//	*Field_Ident
	//	*Field_List
	//	*Field_NonNull
	Type                 isField_Type    `protobuf_oneof:"type"`
	Directives           []*DirectiveLit `protobuf:"bytes,9,rep,name=directives,proto3" json:"directives,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Field) Reset()         { *m = Field{} }
func (m *Field) String() string { return proto.CompactTextString(m) }
func (*Field) ProtoMessage()    {}
func (*Field) Descriptor() ([]byte, []int) {
	return fileDescriptor_37b5b141da493253, []int{3}
}

func (m *Field) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Field.Unmarshal(m, b)
}
func (m *Field) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Field.Marshal(b, m, deterministic)
}
func (m *Field) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Field.Merge(m, src)
}
func (m *Field) XXX_Size() int {
	return xxx_messageInfo_Field.Size(m)
}
func (m *Field) XXX_DiscardUnknown() {
	xxx_messageInfo_Field.DiscardUnknown(m)
}

var xxx_messageInfo_Field proto.InternalMessageInfo

func (m *Field) GetDoc() *DocGroup {
	if m != nil {
		return m.Doc
	}
	return nil
}

func (m *Field) GetName() *Ident {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *Field) GetArgs() *InputValueList {
	if m != nil {
		return m.Args
	}
	return nil
}

type isField_Type interface {
	isField_Type()
}

type Field_Ident struct {
	Ident *Ident `protobuf:"bytes,4,opt,name=ident,proto3,oneof"`
}

type Field_List struct {
	List *List `protobuf:"bytes,5,opt,name=list,proto3,oneof"`
}

type Field_NonNull struct {
	NonNull *NonNull `protobuf:"bytes,6,opt,name=nonNull,proto3,oneof"`
}

func (*Field_Ident) isField_Type() {}

func (*Field_List) isField_Type() {}

func (*Field_NonNull) isField_Type() {}

func (m *Field) GetType() isField_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *Field) GetIdent() *Ident {
	if x, ok := m.GetType().(*Field_Ident); ok {
		return x.Ident
	}
	return nil
}

func (m *Field) GetList() *List {
	if x, ok := m.GetType().(*Field_List); ok {
		return x.List
	}
	return nil
}

func (m *Field) GetNonNull() *NonNull {
	if x, ok := m.GetType().(*Field_NonNull); ok {
		return x.NonNull
	}
	return nil
}

func (m *Field) GetDirectives() []*DirectiveLit {
	if m != nil {
		return m.Directives
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Field) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Field_Ident)(nil),
		(*Field_List)(nil),
		(*Field_NonNull)(nil),
	}
}

// A FieldList represents a list of Fields, enclosed by braces.
type FieldList struct {
	Opening              int64    `protobuf:"varint,1,opt,name=opening,proto3" json:"opening,omitempty"`
	List                 []*Field `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	Closing              int64    `protobuf:"varint,3,opt,name=closing,proto3" json:"closing,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FieldList) Reset()         { *m = FieldList{} }
func (m *FieldList) String() string { return proto.CompactTextString(m) }
func (*FieldList) ProtoMessage()    {}
func (*FieldList) Descriptor() ([]byte, []int) {
	return fileDescriptor_37b5b141da493253, []int{4}
}

func (m *FieldList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FieldList.Unmarshal(m, b)
}
func (m *FieldList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FieldList.Marshal(b, m, deterministic)
}
func (m *FieldList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FieldList.Merge(m, src)
}
func (m *FieldList) XXX_Size() int {
	return xxx_messageInfo_FieldList.Size(m)
}
func (m *FieldList) XXX_DiscardUnknown() {
	xxx_messageInfo_FieldList.DiscardUnknown(m)
}

var xxx_messageInfo_FieldList proto.InternalMessageInfo

func (m *FieldList) GetOpening() int64 {
	if m != nil {
		return m.Opening
	}
	return 0
}

func (m *FieldList) GetList() []*Field {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *FieldList) GetClosing() int64 {
	if m != nil {
		return m.Closing
	}
	return 0
}

// InputValue represents an argument/field which can be used to input data.
type InputValue struct {
	Doc  *DocGroup `protobuf:"bytes,1,opt,name=doc,proto3" json:"doc,omitempty"`
	Name *Ident    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// type
	//
	// Types that are valid to be assigned to Type:
	//	*InputValue_Ident
	//	*InputValue_List
	//	*InputValue_NonNull
	Type isInputValue_Type `protobuf_oneof:"type"`
	// default value; or nil
	//
	// Types that are valid to be assigned to Default:
	//	*InputValue_BasicLit
	//	*InputValue_CompositeLit
	Default              isInputValue_Default `protobuf_oneof:"default"`
	Directives           []*DirectiveLit      `protobuf:"bytes,9,rep,name=directives,proto3" json:"directives,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *InputValue) Reset()         { *m = InputValue{} }
func (m *InputValue) String() string { return proto.CompactTextString(m) }
func (*InputValue) ProtoMessage()    {}
func (*InputValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_37b5b141da493253, []int{5}
}

func (m *InputValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InputValue.Unmarshal(m, b)
}
func (m *InputValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InputValue.Marshal(b, m, deterministic)
}
func (m *InputValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InputValue.Merge(m, src)
}
func (m *InputValue) XXX_Size() int {
	return xxx_messageInfo_InputValue.Size(m)
}
func (m *InputValue) XXX_DiscardUnknown() {
	xxx_messageInfo_InputValue.DiscardUnknown(m)
}

var xxx_messageInfo_InputValue proto.InternalMessageInfo

func (m *InputValue) GetDoc() *DocGroup {
	if m != nil {
		return m.Doc
	}
	return nil
}

func (m *InputValue) GetName() *Ident {
	if m != nil {
		return m.Name
	}
	return nil
}

type isInputValue_Type interface {
	isInputValue_Type()
}

type InputValue_Ident struct {
	Ident *Ident `protobuf:"bytes,3,opt,name=ident,proto3,oneof"`
}

type InputValue_List struct {
	List *List `protobuf:"bytes,4,opt,name=list,proto3,oneof"`
}

type InputValue_NonNull struct {
	NonNull *NonNull `protobuf:"bytes,5,opt,name=nonNull,proto3,oneof"`
}

func (*InputValue_Ident) isInputValue_Type() {}

func (*InputValue_List) isInputValue_Type() {}

func (*InputValue_NonNull) isInputValue_Type() {}

func (m *InputValue) GetType() isInputValue_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *InputValue) GetIdent() *Ident {
	if x, ok := m.GetType().(*InputValue_Ident); ok {
		return x.Ident
	}
	return nil
}

func (m *InputValue) GetList() *List {
	if x, ok := m.GetType().(*InputValue_List); ok {
		return x.List
	}
	return nil
}

func (m *InputValue) GetNonNull() *NonNull {
	if x, ok := m.GetType().(*InputValue_NonNull); ok {
		return x.NonNull
	}
	return nil
}

type isInputValue_Default interface {
	isInputValue_Default()
}

type InputValue_BasicLit struct {
	BasicLit *BasicLit `protobuf:"bytes,6,opt,name=basicLit,proto3,oneof"`
}

type InputValue_CompositeLit struct {
	CompositeLit *CompositeLit `protobuf:"bytes,7,opt,name=compositeLit,proto3,oneof"`
}

func (*InputValue_BasicLit) isInputValue_Default() {}

func (*InputValue_CompositeLit) isInputValue_Default() {}

func (m *InputValue) GetDefault() isInputValue_Default {
	if m != nil {
		return m.Default
	}
	return nil
}

func (m *InputValue) GetBasicLit() *BasicLit {
	if x, ok := m.GetDefault().(*InputValue_BasicLit); ok {
		return x.BasicLit
	}
	return nil
}

func (m *InputValue) GetCompositeLit() *CompositeLit {
	if x, ok := m.GetDefault().(*InputValue_CompositeLit); ok {
		return x.CompositeLit
	}
	return nil
}

func (m *InputValue) GetDirectives() []*DirectiveLit {
	if m != nil {
		return m.Directives
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*InputValue) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*InputValue_Ident)(nil),
		(*InputValue_List)(nil),
		(*InputValue_NonNull)(nil),
		(*InputValue_BasicLit)(nil),
		(*InputValue_CompositeLit)(nil),
	}
}

// InputValueList represents a list of InputValues, enclosed by parentheses or braces.
type InputValueList struct {
	Opening              int64         `protobuf:"varint,1,opt,name=opening,proto3" json:"opening,omitempty"`
	List                 []*InputValue `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	Closing              int64         `protobuf:"varint,3,opt,name=closing,proto3" json:"closing,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *InputValueList) Reset()         { *m = InputValueList{} }
func (m *InputValueList) String() string { return proto.CompactTextString(m) }
func (*InputValueList) ProtoMessage()    {}
func (*InputValueList) Descriptor() ([]byte, []int) {
	return fileDescriptor_37b5b141da493253, []int{6}
}

func (m *InputValueList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InputValueList.Unmarshal(m, b)
}
func (m *InputValueList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InputValueList.Marshal(b, m, deterministic)
}
func (m *InputValueList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InputValueList.Merge(m, src)
}
func (m *InputValueList) XXX_Size() int {
	return xxx_messageInfo_InputValueList.Size(m)
}
func (m *InputValueList) XXX_DiscardUnknown() {
	xxx_messageInfo_InputValueList.DiscardUnknown(m)
}

var xxx_messageInfo_InputValueList proto.InternalMessageInfo

func (m *InputValueList) GetOpening() int64 {
	if m != nil {
		return m.Opening
	}
	return 0
}

func (m *InputValueList) GetList() []*InputValue {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *InputValueList) GetClosing() int64 {
	if m != nil {
		return m.Closing
	}
	return 0
}

// Ident represents an identifier.
type Ident struct {
	NamePos              int64    `protobuf:"varint,1,opt,name=namePos,proto3" json:"namePos,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ident) Reset()         { *m = Ident{} }
func (m *Ident) String() string { return proto.CompactTextString(m) }
func (*Ident) ProtoMessage()    {}
func (*Ident) Descriptor() ([]byte, []int) {
	return fileDescriptor_37b5b141da493253, []int{7}
}

func (m *Ident) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ident.Unmarshal(m, b)
}
func (m *Ident) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ident.Marshal(b, m, deterministic)
}
func (m *Ident) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ident.Merge(m, src)
}
func (m *Ident) XXX_Size() int {
	return xxx_messageInfo_Ident.Size(m)
}
func (m *Ident) XXX_DiscardUnknown() {
	xxx_messageInfo_Ident.DiscardUnknown(m)
}

var xxx_messageInfo_Ident proto.InternalMessageInfo

func (m *Ident) GetNamePos() int64 {
	if m != nil {
		return m.NamePos
	}
	return 0
}

func (m *Ident) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// BasicLit represents a literal of basic type.
type BasicLit struct {
	ValuePos             int64    `protobuf:"varint,1,opt,name=valuePos,proto3" json:"valuePos,omitempty"`
	Kind                 int64    `protobuf:"varint,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Value                string   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BasicLit) Reset()         { *m = BasicLit{} }
func (m *BasicLit) String() string { return proto.CompactTextString(m) }
func (*BasicLit) ProtoMessage()    {}
func (*BasicLit) Descriptor() ([]byte, []int) {
	return fileDescriptor_37b5b141da493253, []int{8}
}

func (m *BasicLit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BasicLit.Unmarshal(m, b)
}
func (m *BasicLit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BasicLit.Marshal(b, m, deterministic)
}
func (m *BasicLit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BasicLit.Merge(m, src)
}
func (m *BasicLit) XXX_Size() int {
	return xxx_messageInfo_BasicLit.Size(m)
}
func (m *BasicLit) XXX_DiscardUnknown() {
	xxx_messageInfo_BasicLit.DiscardUnknown(m)
}

var xxx_messageInfo_BasicLit proto.InternalMessageInfo

func (m *BasicLit) GetValuePos() int64 {
	if m != nil {
		return m.ValuePos
	}
	return 0
}

func (m *BasicLit) GetKind() int64 {
	if m != nil {
		return m.Kind
	}
	return 0
}

func (m *BasicLit) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// CompositeLit represents a composite literal.
type CompositeLit struct {
	Opening int64 `protobuf:"varint,1,opt,name=opening,proto3" json:"opening,omitempty"`
	// Types that are valid to be assigned to Value:
	//	*CompositeLit_BasicLit
	//	*CompositeLit_ListLit
	//	*CompositeLit_ObjLit
	Value                isCompositeLit_Value `protobuf_oneof:"value"`
	Closing              int64                `protobuf:"varint,5,opt,name=closing,proto3" json:"closing,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CompositeLit) Reset()         { *m = CompositeLit{} }
func (m *CompositeLit) String() string { return proto.CompactTextString(m) }
func (*CompositeLit) ProtoMessage()    {}
func (*CompositeLit) Descriptor() ([]byte, []int) {
	return fileDescriptor_37b5b141da493253, []int{9}
}

func (m *CompositeLit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CompositeLit.Unmarshal(m, b)
}
func (m *CompositeLit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CompositeLit.Marshal(b, m, deterministic)
}
func (m *CompositeLit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CompositeLit.Merge(m, src)
}
func (m *CompositeLit) XXX_Size() int {
	return xxx_messageInfo_CompositeLit.Size(m)
}
func (m *CompositeLit) XXX_DiscardUnknown() {
	xxx_messageInfo_CompositeLit.DiscardUnknown(m)
}

var xxx_messageInfo_CompositeLit proto.InternalMessageInfo

func (m *CompositeLit) GetOpening() int64 {
	if m != nil {
		return m.Opening
	}
	return 0
}

type isCompositeLit_Value interface {
	isCompositeLit_Value()
}

type CompositeLit_BasicLit struct {
	BasicLit *BasicLit `protobuf:"bytes,2,opt,name=basicLit,proto3,oneof"`
}

type CompositeLit_ListLit struct {
	ListLit *ListLit `protobuf:"bytes,3,opt,name=listLit,proto3,oneof"`
}

type CompositeLit_ObjLit struct {
	ObjLit *ObjLit `protobuf:"bytes,4,opt,name=objLit,proto3,oneof"`
}

func (*CompositeLit_BasicLit) isCompositeLit_Value() {}

func (*CompositeLit_ListLit) isCompositeLit_Value() {}

func (*CompositeLit_ObjLit) isCompositeLit_Value() {}

func (m *CompositeLit) GetValue() isCompositeLit_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *CompositeLit) GetBasicLit() *BasicLit {
	if x, ok := m.GetValue().(*CompositeLit_BasicLit); ok {
		return x.BasicLit
	}
	return nil
}

func (m *CompositeLit) GetListLit() *ListLit {
	if x, ok := m.GetValue().(*CompositeLit_ListLit); ok {
		return x.ListLit
	}
	return nil
}

func (m *CompositeLit) GetObjLit() *ObjLit {
	if x, ok := m.GetValue().(*CompositeLit_ObjLit); ok {
		return x.ObjLit
	}
	return nil
}

func (m *CompositeLit) GetClosing() int64 {
	if m != nil {
		return m.Closing
	}
	return 0
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*CompositeLit) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*CompositeLit_BasicLit)(nil),
		(*CompositeLit_ListLit)(nil),
		(*CompositeLit_ObjLit)(nil),
	}
}

// ListLit represents a list literal value.
type ListLit struct {
	// Types that are valid to be assigned to List:
	//	*ListLit_BasicList
	//	*ListLit_CompositeList
	List                 isListLit_List `protobuf_oneof:"list"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ListLit) Reset()         { *m = ListLit{} }
func (m *ListLit) String() string { return proto.CompactTextString(m) }
func (*ListLit) ProtoMessage()    {}
func (*ListLit) Descriptor() ([]byte, []int) {
	return fileDescriptor_37b5b141da493253, []int{10}
}

func (m *ListLit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListLit.Unmarshal(m, b)
}
func (m *ListLit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListLit.Marshal(b, m, deterministic)
}
func (m *ListLit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListLit.Merge(m, src)
}
func (m *ListLit) XXX_Size() int {
	return xxx_messageInfo_ListLit.Size(m)
}
func (m *ListLit) XXX_DiscardUnknown() {
	xxx_messageInfo_ListLit.DiscardUnknown(m)
}

var xxx_messageInfo_ListLit proto.InternalMessageInfo

type isListLit_List interface {
	isListLit_List()
}

type ListLit_BasicList struct {
	BasicList *ListLit_Basic `protobuf:"bytes,1,opt,name=basicList,proto3,oneof"`
}

type ListLit_CompositeList struct {
	CompositeList *ListLit_Composite `protobuf:"bytes,2,opt,name=compositeList,proto3,oneof"`
}

func (*ListLit_BasicList) isListLit_List() {}

func (*ListLit_CompositeList) isListLit_List() {}

func (m *ListLit) GetList() isListLit_List {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *ListLit) GetBasicList() *ListLit_Basic {
	if x, ok := m.GetList().(*ListLit_BasicList); ok {
		return x.BasicList
	}
	return nil
}

func (m *ListLit) GetCompositeList() *ListLit_Composite {
	if x, ok := m.GetList().(*ListLit_CompositeList); ok {
		return x.CompositeList
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ListLit) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ListLit_BasicList)(nil),
		(*ListLit_CompositeList)(nil),
	}
}

type ListLit_Basic struct {
	Values               []*BasicLit `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ListLit_Basic) Reset()         { *m = ListLit_Basic{} }
func (m *ListLit_Basic) String() string { return proto.CompactTextString(m) }
func (*ListLit_Basic) ProtoMessage()    {}
func (*ListLit_Basic) Descriptor() ([]byte, []int) {
	return fileDescriptor_37b5b141da493253, []int{10, 0}
}

func (m *ListLit_Basic) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListLit_Basic.Unmarshal(m, b)
}
func (m *ListLit_Basic) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListLit_Basic.Marshal(b, m, deterministic)
}
func (m *ListLit_Basic) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListLit_Basic.Merge(m, src)
}
func (m *ListLit_Basic) XXX_Size() int {
	return xxx_messageInfo_ListLit_Basic.Size(m)
}
func (m *ListLit_Basic) XXX_DiscardUnknown() {
	xxx_messageInfo_ListLit_Basic.DiscardUnknown(m)
}

var xxx_messageInfo_ListLit_Basic proto.InternalMessageInfo

func (m *ListLit_Basic) GetValues() []*BasicLit {
	if m != nil {
		return m.Values
	}
	return nil
}

type ListLit_Composite struct {
	Values               []*CompositeLit `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ListLit_Composite) Reset()         { *m = ListLit_Composite{} }
func (m *ListLit_Composite) String() string { return proto.CompactTextString(m) }
func (*ListLit_Composite) ProtoMessage()    {}
func (*ListLit_Composite) Descriptor() ([]byte, []int) {
	return fileDescriptor_37b5b141da493253, []int{10, 1}
}

func (m *ListLit_Composite) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListLit_Composite.Unmarshal(m, b)
}
func (m *ListLit_Composite) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListLit_Composite.Marshal(b, m, deterministic)
}
func (m *ListLit_Composite) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListLit_Composite.Merge(m, src)
}
func (m *ListLit_Composite) XXX_Size() int {
	return xxx_messageInfo_ListLit_Composite.Size(m)
}
func (m *ListLit_Composite) XXX_DiscardUnknown() {
	xxx_messageInfo_ListLit_Composite.DiscardUnknown(m)
}

var xxx_messageInfo_ListLit_Composite proto.InternalMessageInfo

func (m *ListLit_Composite) GetValues() []*CompositeLit {
	if m != nil {
		return m.Values
	}
	return nil
}

// ObjLit represents an object literal.
type ObjLit struct {
	Fields               []*ObjLit_Pair `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ObjLit) Reset()         { *m = ObjLit{} }
func (m *ObjLit) String() string { return proto.CompactTextString(m) }
func (*ObjLit) ProtoMessage()    {}
func (*ObjLit) Descriptor() ([]byte, []int) {
	return fileDescriptor_37b5b141da493253, []int{11}
}

func (m *ObjLit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObjLit.Unmarshal(m, b)
}
func (m *ObjLit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObjLit.Marshal(b, m, deterministic)
}
func (m *ObjLit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjLit.Merge(m, src)
}
func (m *ObjLit) XXX_Size() int {
	return xxx_messageInfo_ObjLit.Size(m)
}
func (m *ObjLit) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjLit.DiscardUnknown(m)
}

var xxx_messageInfo_ObjLit proto.InternalMessageInfo

func (m *ObjLit) GetFields() []*ObjLit_Pair {
	if m != nil {
		return m.Fields
	}
	return nil
}

type ObjLit_Pair struct {
	Key                  *Ident        `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Val                  *CompositeLit `protobuf:"bytes,2,opt,name=val,proto3" json:"val,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ObjLit_Pair) Reset()         { *m = ObjLit_Pair{} }
func (m *ObjLit_Pair) String() string { return proto.CompactTextString(m) }
func (*ObjLit_Pair) ProtoMessage()    {}
func (*ObjLit_Pair) Descriptor() ([]byte, []int) {
	return fileDescriptor_37b5b141da493253, []int{11, 0}
}

func (m *ObjLit_Pair) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObjLit_Pair.Unmarshal(m, b)
}
func (m *ObjLit_Pair) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObjLit_Pair.Marshal(b, m, deterministic)
}
func (m *ObjLit_Pair) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjLit_Pair.Merge(m, src)
}
func (m *ObjLit_Pair) XXX_Size() int {
	return xxx_messageInfo_ObjLit_Pair.Size(m)
}
func (m *ObjLit_Pair) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjLit_Pair.DiscardUnknown(m)
}

var xxx_messageInfo_ObjLit_Pair proto.InternalMessageInfo

func (m *ObjLit_Pair) GetKey() *Ident {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *ObjLit_Pair) GetVal() *CompositeLit {
	if m != nil {
		return m.Val
	}
	return nil
}

// List represents a List type.
type List struct {
	// Types that are valid to be assigned to Type:
	//	*List_Ident
	//	*List_List
	//	*List_NonNull
	Type                 isList_Type `protobuf_oneof:"type"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *List) Reset()         { *m = List{} }
func (m *List) String() string { return proto.CompactTextString(m) }
func (*List) ProtoMessage()    {}
func (*List) Descriptor() ([]byte, []int) {
	return fileDescriptor_37b5b141da493253, []int{12}
}

func (m *List) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_List.Unmarshal(m, b)
}
func (m *List) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_List.Marshal(b, m, deterministic)
}
func (m *List) XXX_Merge(src proto.Message) {
	xxx_messageInfo_List.Merge(m, src)
}
func (m *List) XXX_Size() int {
	return xxx_messageInfo_List.Size(m)
}
func (m *List) XXX_DiscardUnknown() {
	xxx_messageInfo_List.DiscardUnknown(m)
}

var xxx_messageInfo_List proto.InternalMessageInfo

type isList_Type interface {
	isList_Type()
}

type List_Ident struct {
	Ident *Ident `protobuf:"bytes,1,opt,name=ident,proto3,oneof"`
}

type List_List struct {
	List *List `protobuf:"bytes,2,opt,name=list,proto3,oneof"`
}

type List_NonNull struct {
	NonNull *NonNull `protobuf:"bytes,3,opt,name=nonNull,proto3,oneof"`
}

func (*List_Ident) isList_Type() {}

func (*List_List) isList_Type() {}

func (*List_NonNull) isList_Type() {}

func (m *List) GetType() isList_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *List) GetIdent() *Ident {
	if x, ok := m.GetType().(*List_Ident); ok {
		return x.Ident
	}
	return nil
}

func (m *List) GetList() *List {
	if x, ok := m.GetType().(*List_List); ok {
		return x.List
	}
	return nil
}

func (m *List) GetNonNull() *NonNull {
	if x, ok := m.GetType().(*List_NonNull); ok {
		return x.NonNull
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*List) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*List_Ident)(nil),
		(*List_List)(nil),
		(*List_NonNull)(nil),
	}
}

// NonNull represents an identifier with the non-null character, '!', after it.
type NonNull struct {
	// Types that are valid to be assigned to Type:
	//	*NonNull_Ident
	//	*NonNull_List
	Type                 isNonNull_Type `protobuf_oneof:"type"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *NonNull) Reset()         { *m = NonNull{} }
func (m *NonNull) String() string { return proto.CompactTextString(m) }
func (*NonNull) ProtoMessage()    {}
func (*NonNull) Descriptor() ([]byte, []int) {
	return fileDescriptor_37b5b141da493253, []int{13}
}

func (m *NonNull) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NonNull.Unmarshal(m, b)
}
func (m *NonNull) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NonNull.Marshal(b, m, deterministic)
}
func (m *NonNull) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NonNull.Merge(m, src)
}
func (m *NonNull) XXX_Size() int {
	return xxx_messageInfo_NonNull.Size(m)
}
func (m *NonNull) XXX_DiscardUnknown() {
	xxx_messageInfo_NonNull.DiscardUnknown(m)
}

var xxx_messageInfo_NonNull proto.InternalMessageInfo

type isNonNull_Type interface {
	isNonNull_Type()
}

type NonNull_Ident struct {
	Ident *Ident `protobuf:"bytes,1,opt,name=ident,proto3,oneof"`
}

type NonNull_List struct {
	List *List `protobuf:"bytes,2,opt,name=list,proto3,oneof"`
}

func (*NonNull_Ident) isNonNull_Type() {}

func (*NonNull_List) isNonNull_Type() {}

func (m *NonNull) GetType() isNonNull_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *NonNull) GetIdent() *Ident {
	if x, ok := m.GetType().(*NonNull_Ident); ok {
		return x.Ident
	}
	return nil
}

func (m *NonNull) GetList() *List {
	if x, ok := m.GetType().(*NonNull_List); ok {
		return x.List
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*NonNull) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*NonNull_Ident)(nil),
		(*NonNull_List)(nil),
	}
}

// DirectiveLit presents an applied directive
type DirectiveLit struct {
	AtPos                int64     `protobuf:"varint,1,opt,name=atPos,proto3" json:"atPos,omitempty"`
	Name                 string    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Args                 *CallExpr `protobuf:"bytes,3,opt,name=args,proto3" json:"args,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *DirectiveLit) Reset()         { *m = DirectiveLit{} }
func (m *DirectiveLit) String() string { return proto.CompactTextString(m) }
func (*DirectiveLit) ProtoMessage()    {}
func (*DirectiveLit) Descriptor() ([]byte, []int) {
	return fileDescriptor_37b5b141da493253, []int{14}
}

func (m *DirectiveLit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DirectiveLit.Unmarshal(m, b)
}
func (m *DirectiveLit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DirectiveLit.Marshal(b, m, deterministic)
}
func (m *DirectiveLit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DirectiveLit.Merge(m, src)
}
func (m *DirectiveLit) XXX_Size() int {
	return xxx_messageInfo_DirectiveLit.Size(m)
}
func (m *DirectiveLit) XXX_DiscardUnknown() {
	xxx_messageInfo_DirectiveLit.DiscardUnknown(m)
}

var xxx_messageInfo_DirectiveLit proto.InternalMessageInfo

func (m *DirectiveLit) GetAtPos() int64 {
	if m != nil {
		return m.AtPos
	}
	return 0
}

func (m *DirectiveLit) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DirectiveLit) GetArgs() *CallExpr {
	if m != nil {
		return m.Args
	}
	return nil
}

// DirectiveLocation represents a defined directive location in a directive declaration.
type DirectiveLocation struct {
	Start                int64                 `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"`
	Loc                  DirectiveLocation_Loc `protobuf:"varint,2,opt,name=loc,proto3,enum=DirectiveLocation_Loc" json:"loc,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *DirectiveLocation) Reset()         { *m = DirectiveLocation{} }
func (m *DirectiveLocation) String() string { return proto.CompactTextString(m) }
func (*DirectiveLocation) ProtoMessage()    {}
func (*DirectiveLocation) Descriptor() ([]byte, []int) {
	return fileDescriptor_37b5b141da493253, []int{15}
}

func (m *DirectiveLocation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DirectiveLocation.Unmarshal(m, b)
}
func (m *DirectiveLocation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DirectiveLocation.Marshal(b, m, deterministic)
}
func (m *DirectiveLocation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DirectiveLocation.Merge(m, src)
}
func (m *DirectiveLocation) XXX_Size() int {
	return xxx_messageInfo_DirectiveLocation.Size(m)
}
func (m *DirectiveLocation) XXX_DiscardUnknown() {
	xxx_messageInfo_DirectiveLocation.DiscardUnknown(m)
}

var xxx_messageInfo_DirectiveLocation proto.InternalMessageInfo

func (m *DirectiveLocation) GetStart() int64 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *DirectiveLocation) GetLoc() DirectiveLocation_Loc {
	if m != nil {
		return m.Loc
	}
	return DirectiveLocation_NoPos
}

// CallExpr represents an expression followed by an argument list.
type CallExpr struct {
	Lparen               int64    `protobuf:"varint,1,opt,name=lparen,proto3" json:"lparen,omitempty"`
	Args                 []*Arg   `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	Rparen               int64    `protobuf:"varint,3,opt,name=rparen,proto3" json:"rparen,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CallExpr) Reset()         { *m = CallExpr{} }
func (m *CallExpr) String() string { return proto.CompactTextString(m) }
func (*CallExpr) ProtoMessage()    {}
func (*CallExpr) Descriptor() ([]byte, []int) {
	return fileDescriptor_37b5b141da493253, []int{16}
}

func (m *CallExpr) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CallExpr.Unmarshal(m, b)
}
func (m *CallExpr) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CallExpr.Marshal(b, m, deterministic)
}
func (m *CallExpr) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CallExpr.Merge(m, src)
}
func (m *CallExpr) XXX_Size() int {
	return xxx_messageInfo_CallExpr.Size(m)
}
func (m *CallExpr) XXX_DiscardUnknown() {
	xxx_messageInfo_CallExpr.DiscardUnknown(m)
}

var xxx_messageInfo_CallExpr proto.InternalMessageInfo

func (m *CallExpr) GetLparen() int64 {
	if m != nil {
		return m.Lparen
	}
	return 0
}

func (m *CallExpr) GetArgs() []*Arg {
	if m != nil {
		return m.Args
	}
	return nil
}

func (m *CallExpr) GetRparen() int64 {
	if m != nil {
		return m.Rparen
	}
	return 0
}

// SchemaType represents a schema type declaration.
type SchemaType struct {
	Schema               int64      `protobuf:"varint,1,opt,name=schema,proto3" json:"schema,omitempty"`
	RootOps              *FieldList `protobuf:"bytes,2,opt,name=rootOps,proto3" json:"rootOps,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SchemaType) Reset()         { *m = SchemaType{} }
func (m *SchemaType) String() string { return proto.CompactTextString(m) }
func (*SchemaType) ProtoMessage()    {}
func (*SchemaType) Descriptor() ([]byte, []int) {
	return fileDescriptor_37b5b141da493253, []int{17}
}

func (m *SchemaType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SchemaType.Unmarshal(m, b)
}
func (m *SchemaType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SchemaType.Marshal(b, m, deterministic)
}
func (m *SchemaType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SchemaType.Merge(m, src)
}
func (m *SchemaType) XXX_Size() int {
	return xxx_messageInfo_SchemaType.Size(m)
}
func (m *SchemaType) XXX_DiscardUnknown() {
	xxx_messageInfo_SchemaType.DiscardUnknown(m)
}

var xxx_messageInfo_SchemaType proto.InternalMessageInfo

func (m *SchemaType) GetSchema() int64 {
	if m != nil {
		return m.Schema
	}
	return 0
}

func (m *SchemaType) GetRootOps() *FieldList {
	if m != nil {
		return m.RootOps
	}
	return nil
}

// ScalarType represents a scalar type declaration.
type ScalarType struct {
	Scalar               int64    `protobuf:"varint,1,opt,name=scalar,proto3" json:"scalar,omitempty"`
	Name                 *Ident   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ScalarType) Reset()         { *m = ScalarType{} }
func (m *ScalarType) String() string { return proto.CompactTextString(m) }
func (*ScalarType) ProtoMessage()    {}
func (*ScalarType) Descriptor() ([]byte, []int) {
	return fileDescriptor_37b5b141da493253, []int{18}
}

func (m *ScalarType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScalarType.Unmarshal(m, b)
}
func (m *ScalarType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScalarType.Marshal(b, m, deterministic)
}
func (m *ScalarType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScalarType.Merge(m, src)
}
func (m *ScalarType) XXX_Size() int {
	return xxx_messageInfo_ScalarType.Size(m)
}
func (m *ScalarType) XXX_DiscardUnknown() {
	xxx_messageInfo_ScalarType.DiscardUnknown(m)
}

var xxx_messageInfo_ScalarType proto.InternalMessageInfo

func (m *ScalarType) GetScalar() int64 {
	if m != nil {
		return m.Scalar
	}
	return 0
}

func (m *ScalarType) GetName() *Ident {
	if m != nil {
		return m.Name
	}
	return nil
}

// ObjectType represents an object type declaration.
type ObjectType struct {
	Object               int64      `protobuf:"varint,1,opt,name=object,proto3" json:"object,omitempty"`
	ImplPos              int64      `protobuf:"varint,2,opt,name=implPos,proto3" json:"implPos,omitempty"`
	Interfaces           []*Ident   `protobuf:"bytes,3,rep,name=interfaces,proto3" json:"interfaces,omitempty"`
	Fields               *FieldList `protobuf:"bytes,4,opt,name=fields,proto3" json:"fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ObjectType) Reset()         { *m = ObjectType{} }
func (m *ObjectType) String() string { return proto.CompactTextString(m) }
func (*ObjectType) ProtoMessage()    {}
func (*ObjectType) Descriptor() ([]byte, []int) {
	return fileDescriptor_37b5b141da493253, []int{19}
}

func (m *ObjectType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObjectType.Unmarshal(m, b)
}
func (m *ObjectType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObjectType.Marshal(b, m, deterministic)
}
func (m *ObjectType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjectType.Merge(m, src)
}
func (m *ObjectType) XXX_Size() int {
	return xxx_messageInfo_ObjectType.Size(m)
}
func (m *ObjectType) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjectType.DiscardUnknown(m)
}

var xxx_messageInfo_ObjectType proto.InternalMessageInfo

func (m *ObjectType) GetObject() int64 {
	if m != nil {
		return m.Object
	}
	return 0
}

func (m *ObjectType) GetImplPos() int64 {
	if m != nil {
		return m.ImplPos
	}
	return 0
}

func (m *ObjectType) GetInterfaces() []*Ident {
	if m != nil {
		return m.Interfaces
	}
	return nil
}

func (m *ObjectType) GetFields() *FieldList {
	if m != nil {
		return m.Fields
	}
	return nil
}

// InterfaceType represents an interface type declaration.
type InterfaceType struct {
	Interface            int64      `protobuf:"varint,1,opt,name=interface,proto3" json:"interface,omitempty"`
	Fields               *FieldList `protobuf:"bytes,2,opt,name=fields,proto3" json:"fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *InterfaceType) Reset()         { *m = InterfaceType{} }
func (m *InterfaceType) String() string { return proto.CompactTextString(m) }
func (*InterfaceType) ProtoMessage()    {}
func (*InterfaceType) Descriptor() ([]byte, []int) {
	return fileDescriptor_37b5b141da493253, []int{20}
}

func (m *InterfaceType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InterfaceType.Unmarshal(m, b)
}
func (m *InterfaceType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InterfaceType.Marshal(b, m, deterministic)
}
func (m *InterfaceType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InterfaceType.Merge(m, src)
}
func (m *InterfaceType) XXX_Size() int {
	return xxx_messageInfo_InterfaceType.Size(m)
}
func (m *InterfaceType) XXX_DiscardUnknown() {
	xxx_messageInfo_InterfaceType.DiscardUnknown(m)
}

var xxx_messageInfo_InterfaceType proto.InternalMessageInfo

func (m *InterfaceType) GetInterface() int64 {
	if m != nil {
		return m.Interface
	}
	return 0
}

func (m *InterfaceType) GetFields() *FieldList {
	if m != nil {
		return m.Fields
	}
	return nil
}

// UnionType represents a union type declaration.
type UnionType struct {
	Union                int64    `protobuf:"varint,1,opt,name=union,proto3" json:"union,omitempty"`
	Members              []*Ident `protobuf:"bytes,2,rep,name=members,proto3" json:"members,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnionType) Reset()         { *m = UnionType{} }
func (m *UnionType) String() string { return proto.CompactTextString(m) }
func (*UnionType) ProtoMessage()    {}
func (*UnionType) Descriptor() ([]byte, []int) {
	return fileDescriptor_37b5b141da493253, []int{21}
}

func (m *UnionType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnionType.Unmarshal(m, b)
}
func (m *UnionType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnionType.Marshal(b, m, deterministic)
}
func (m *UnionType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnionType.Merge(m, src)
}
func (m *UnionType) XXX_Size() int {
	return xxx_messageInfo_UnionType.Size(m)
}
func (m *UnionType) XXX_DiscardUnknown() {
	xxx_messageInfo_UnionType.DiscardUnknown(m)
}

var xxx_messageInfo_UnionType proto.InternalMessageInfo

func (m *UnionType) GetUnion() int64 {
	if m != nil {
		return m.Union
	}
	return 0
}

func (m *UnionType) GetMembers() []*Ident {
	if m != nil {
		return m.Members
	}
	return nil
}

// EnumType represents an enum type declaration.
type EnumType struct {
	Enum                 int64      `protobuf:"varint,1,opt,name=enum,proto3" json:"enum,omitempty"`
	Values               *FieldList `protobuf:"bytes,2,opt,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *EnumType) Reset()         { *m = EnumType{} }
func (m *EnumType) String() string { return proto.CompactTextString(m) }
func (*EnumType) ProtoMessage()    {}
func (*EnumType) Descriptor() ([]byte, []int) {
	return fileDescriptor_37b5b141da493253, []int{22}
}

func (m *EnumType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnumType.Unmarshal(m, b)
}
func (m *EnumType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnumType.Marshal(b, m, deterministic)
}
func (m *EnumType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnumType.Merge(m, src)
}
func (m *EnumType) XXX_Size() int {
	return xxx_messageInfo_EnumType.Size(m)
}
func (m *EnumType) XXX_DiscardUnknown() {
	xxx_messageInfo_EnumType.DiscardUnknown(m)
}

var xxx_messageInfo_EnumType proto.InternalMessageInfo

func (m *EnumType) GetEnum() int64 {
	if m != nil {
		return m.Enum
	}
	return 0
}

func (m *EnumType) GetValues() *FieldList {
	if m != nil {
		return m.Values
	}
	return nil
}

// InputType represents an input type declaration.
type InputType struct {
	Input                int64           `protobuf:"varint,1,opt,name=input,proto3" json:"input,omitempty"`
	Fields               *InputValueList `protobuf:"bytes,2,opt,name=fields,proto3" json:"fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *InputType) Reset()         { *m = InputType{} }
func (m *InputType) String() string { return proto.CompactTextString(m) }
func (*InputType) ProtoMessage()    {}
func (*InputType) Descriptor() ([]byte, []int) {
	return fileDescriptor_37b5b141da493253, []int{23}
}

func (m *InputType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InputType.Unmarshal(m, b)
}
func (m *InputType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InputType.Marshal(b, m, deterministic)
}
func (m *InputType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InputType.Merge(m, src)
}
func (m *InputType) XXX_Size() int {
	return xxx_messageInfo_InputType.Size(m)
}
func (m *InputType) XXX_DiscardUnknown() {
	xxx_messageInfo_InputType.DiscardUnknown(m)
}

var xxx_messageInfo_InputType proto.InternalMessageInfo

func (m *InputType) GetInput() int64 {
	if m != nil {
		return m.Input
	}
	return 0
}

func (m *InputType) GetFields() *InputValueList {
	if m != nil {
		return m.Fields
	}
	return nil
}

// DirectiveType represents a directive type declaration.
type DirectiveType struct {
	Directive            int64                `protobuf:"varint,1,opt,name=directive,proto3" json:"directive,omitempty"`
	Args                 *InputValueList      `protobuf:"bytes,2,opt,name=args,proto3" json:"args,omitempty"`
	OnPos                int64                `protobuf:"varint,3,opt,name=onPos,proto3" json:"onPos,omitempty"`
	Locs                 []*DirectiveLocation `protobuf:"bytes,4,rep,name=locs,proto3" json:"locs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *DirectiveType) Reset()         { *m = DirectiveType{} }
func (m *DirectiveType) String() string { return proto.CompactTextString(m) }
func (*DirectiveType) ProtoMessage()    {}
func (*DirectiveType) Descriptor() ([]byte, []int) {
	return fileDescriptor_37b5b141da493253, []int{24}
}

func (m *DirectiveType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DirectiveType.Unmarshal(m, b)
}
func (m *DirectiveType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DirectiveType.Marshal(b, m, deterministic)
}
func (m *DirectiveType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DirectiveType.Merge(m, src)
}
func (m *DirectiveType) XXX_Size() int {
	return xxx_messageInfo_DirectiveType.Size(m)
}
func (m *DirectiveType) XXX_DiscardUnknown() {
	xxx_messageInfo_DirectiveType.DiscardUnknown(m)
}

var xxx_messageInfo_DirectiveType proto.InternalMessageInfo

func (m *DirectiveType) GetDirective() int64 {
	if m != nil {
		return m.Directive
	}
	return 0
}

func (m *DirectiveType) GetArgs() *InputValueList {
	if m != nil {
		return m.Args
	}
	return nil
}

func (m *DirectiveType) GetOnPos() int64 {
	if m != nil {
		return m.OnPos
	}
	return 0
}

func (m *DirectiveType) GetLocs() []*DirectiveLocation {
	if m != nil {
		return m.Locs
	}
	return nil
}

// A TypeSpec node represents a GraphQL type declaration.
type TypeSpec struct {
	Doc  *DocGroup `protobuf:"bytes,1,opt,name=doc,proto3" json:"doc,omitempty"`
	Name *Ident    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Types that are valid to be assigned to Type:
	//	*TypeSpec_Schema
	//	*TypeSpec_Scalar
	//	*TypeSpec_Object
	//	*TypeSpec_Interface
	//	*TypeSpec_Union
	//	*TypeSpec_Enum
	//	*TypeSpec_Input
	//	*TypeSpec_Directive
	Type                 isTypeSpec_Type `protobuf_oneof:"type"`
	Directives           []*DirectiveLit `protobuf:"bytes,11,rep,name=directives,proto3" json:"directives,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *TypeSpec) Reset()         { *m = TypeSpec{} }
func (m *TypeSpec) String() string { return proto.CompactTextString(m) }
func (*TypeSpec) ProtoMessage()    {}
func (*TypeSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_37b5b141da493253, []int{25}
}

func (m *TypeSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TypeSpec.Unmarshal(m, b)
}
func (m *TypeSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TypeSpec.Marshal(b, m, deterministic)
}
func (m *TypeSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TypeSpec.Merge(m, src)
}
func (m *TypeSpec) XXX_Size() int {
	return xxx_messageInfo_TypeSpec.Size(m)
}
func (m *TypeSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_TypeSpec.DiscardUnknown(m)
}

var xxx_messageInfo_TypeSpec proto.InternalMessageInfo

func (m *TypeSpec) GetDoc() *DocGroup {
	if m != nil {
		return m.Doc
	}
	return nil
}

func (m *TypeSpec) GetName() *Ident {
	if m != nil {
		return m.Name
	}
	return nil
}

type isTypeSpec_Type interface {
	isTypeSpec_Type()
}

type TypeSpec_Schema struct {
	Schema *SchemaType `protobuf:"bytes,3,opt,name=schema,proto3,oneof"`
}

type TypeSpec_Scalar struct {
	Scalar *ScalarType `protobuf:"bytes,4,opt,name=scalar,proto3,oneof"`
}

type TypeSpec_Object struct {
	Object *ObjectType `protobuf:"bytes,5,opt,name=object,proto3,oneof"`
}

type TypeSpec_Interface struct {
	Interface *InterfaceType `protobuf:"bytes,6,opt,name=interface,proto3,oneof"`
}

type TypeSpec_Union struct {
	Union *UnionType `protobuf:"bytes,7,opt,name=union,proto3,oneof"`
}

type TypeSpec_Enum struct {
	Enum *EnumType `protobuf:"bytes,8,opt,name=enum,proto3,oneof"`
}

type TypeSpec_Input struct {
	Input *InputType `protobuf:"bytes,9,opt,name=input,proto3,oneof"`
}

type TypeSpec_Directive struct {
	Directive *DirectiveType `protobuf:"bytes,10,opt,name=directive,proto3,oneof"`
}

func (*TypeSpec_Schema) isTypeSpec_Type() {}

func (*TypeSpec_Scalar) isTypeSpec_Type() {}

func (*TypeSpec_Object) isTypeSpec_Type() {}

func (*TypeSpec_Interface) isTypeSpec_Type() {}

func (*TypeSpec_Union) isTypeSpec_Type() {}

func (*TypeSpec_Enum) isTypeSpec_Type() {}

func (*TypeSpec_Input) isTypeSpec_Type() {}

func (*TypeSpec_Directive) isTypeSpec_Type() {}

func (m *TypeSpec) GetType() isTypeSpec_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *TypeSpec) GetSchema() *SchemaType {
	if x, ok := m.GetType().(*TypeSpec_Schema); ok {
		return x.Schema
	}
	return nil
}

func (m *TypeSpec) GetScalar() *ScalarType {
	if x, ok := m.GetType().(*TypeSpec_Scalar); ok {
		return x.Scalar
	}
	return nil
}

func (m *TypeSpec) GetObject() *ObjectType {
	if x, ok := m.GetType().(*TypeSpec_Object); ok {
		return x.Object
	}
	return nil
}

func (m *TypeSpec) GetInterface() *InterfaceType {
	if x, ok := m.GetType().(*TypeSpec_Interface); ok {
		return x.Interface
	}
	return nil
}

func (m *TypeSpec) GetUnion() *UnionType {
	if x, ok := m.GetType().(*TypeSpec_Union); ok {
		return x.Union
	}
	return nil
}

func (m *TypeSpec) GetEnum() *EnumType {
	if x, ok := m.GetType().(*TypeSpec_Enum); ok {
		return x.Enum
	}
	return nil
}

func (m *TypeSpec) GetInput() *InputType {
	if x, ok := m.GetType().(*TypeSpec_Input); ok {
		return x.Input
	}
	return nil
}

func (m *TypeSpec) GetDirective() *DirectiveType {
	if x, ok := m.GetType().(*TypeSpec_Directive); ok {
		return x.Directive
	}
	return nil
}

func (m *TypeSpec) GetDirectives() []*DirectiveLit {
	if m != nil {
		return m.Directives
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*TypeSpec) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*TypeSpec_Schema)(nil),
		(*TypeSpec_Scalar)(nil),
		(*TypeSpec_Object)(nil),
		(*TypeSpec_Interface)(nil),
		(*TypeSpec_Union)(nil),
		(*TypeSpec_Enum)(nil),
		(*TypeSpec_Input)(nil),
		(*TypeSpec_Directive)(nil),
	}
}

// A TypeExtensionSpec node represents a GraphQL type extension.
type TypeExtensionSpec struct {
	Doc                  *DocGroup `protobuf:"bytes,1,opt,name=doc,proto3" json:"doc,omitempty"`
	Type                 *TypeSpec `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *TypeExtensionSpec) Reset()         { *m = TypeExtensionSpec{} }
func (m *TypeExtensionSpec) String() string { return proto.CompactTextString(m) }
func (*TypeExtensionSpec) ProtoMessage()    {}
func (*TypeExtensionSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_37b5b141da493253, []int{26}
}

func (m *TypeExtensionSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TypeExtensionSpec.Unmarshal(m, b)
}
func (m *TypeExtensionSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TypeExtensionSpec.Marshal(b, m, deterministic)
}
func (m *TypeExtensionSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TypeExtensionSpec.Merge(m, src)
}
func (m *TypeExtensionSpec) XXX_Size() int {
	return xxx_messageInfo_TypeExtensionSpec.Size(m)
}
func (m *TypeExtensionSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_TypeExtensionSpec.DiscardUnknown(m)
}

var xxx_messageInfo_TypeExtensionSpec proto.InternalMessageInfo

func (m *TypeExtensionSpec) GetDoc() *DocGroup {
	if m != nil {
		return m.Doc
	}
	return nil
}

func (m *TypeExtensionSpec) GetType() *TypeSpec {
	if m != nil {
		return m.Type
	}
	return nil
}

// TypeDecl represents a general type declaration.
type TypeDecl struct {
	Doc    *DocGroup `protobuf:"bytes,1,opt,name=doc,proto3" json:"doc,omitempty"`
	TokPos int64     `protobuf:"varint,2,opt,name=tokPos,proto3" json:"tokPos,omitempty"`
	Tok    int64     `protobuf:"varint,3,opt,name=tok,proto3" json:"tok,omitempty"`
	// Types that are valid to be assigned to Spec:
	//	*TypeDecl_TypeSpec
	//	*TypeDecl_TypeExtSpec
	Spec                 isTypeDecl_Spec `protobuf_oneof:"spec"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *TypeDecl) Reset()         { *m = TypeDecl{} }
func (m *TypeDecl) String() string { return proto.CompactTextString(m) }
func (*TypeDecl) ProtoMessage()    {}
func (*TypeDecl) Descriptor() ([]byte, []int) {
	return fileDescriptor_37b5b141da493253, []int{27}
}

func (m *TypeDecl) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TypeDecl.Unmarshal(m, b)
}
func (m *TypeDecl) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TypeDecl.Marshal(b, m, deterministic)
}
func (m *TypeDecl) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TypeDecl.Merge(m, src)
}
func (m *TypeDecl) XXX_Size() int {
	return xxx_messageInfo_TypeDecl.Size(m)
}
func (m *TypeDecl) XXX_DiscardUnknown() {
	xxx_messageInfo_TypeDecl.DiscardUnknown(m)
}

var xxx_messageInfo_TypeDecl proto.InternalMessageInfo

func (m *TypeDecl) GetDoc() *DocGroup {
	if m != nil {
		return m.Doc
	}
	return nil
}

func (m *TypeDecl) GetTokPos() int64 {
	if m != nil {
		return m.TokPos
	}
	return 0
}

func (m *TypeDecl) GetTok() int64 {
	if m != nil {
		return m.Tok
	}
	return 0
}

type isTypeDecl_Spec interface {
	isTypeDecl_Spec()
}

type TypeDecl_TypeSpec struct {
	TypeSpec *TypeSpec `protobuf:"bytes,4,opt,name=typeSpec,proto3,oneof"`
}

type TypeDecl_TypeExtSpec struct {
	TypeExtSpec *TypeExtensionSpec `protobuf:"bytes,5,opt,name=typeExtSpec,proto3,oneof"`
}

func (*TypeDecl_TypeSpec) isTypeDecl_Spec() {}

func (*TypeDecl_TypeExtSpec) isTypeDecl_Spec() {}

func (m *TypeDecl) GetSpec() isTypeDecl_Spec {
	if m != nil {
		return m.Spec
	}
	return nil
}

func (m *TypeDecl) GetTypeSpec() *TypeSpec {
	if x, ok := m.GetSpec().(*TypeDecl_TypeSpec); ok {
		return x.TypeSpec
	}
	return nil
}

func (m *TypeDecl) GetTypeExtSpec() *TypeExtensionSpec {
	if x, ok := m.GetSpec().(*TypeDecl_TypeExtSpec); ok {
		return x.TypeExtSpec
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*TypeDecl) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*TypeDecl_TypeSpec)(nil),
		(*TypeDecl_TypeExtSpec)(nil),
	}
}

func init() {
	proto.RegisterEnum("DirectiveLocation_Loc", DirectiveLocation_Loc_name, DirectiveLocation_Loc_value)
	proto.RegisterType((*Document)(nil), "Document")
	proto.RegisterType((*DocGroup)(nil), "DocGroup")
	proto.RegisterType((*DocGroup_Doc)(nil), "DocGroup.Doc")
	proto.RegisterType((*Arg)(nil), "Arg")
	proto.RegisterType((*Field)(nil), "Field")
	proto.RegisterType((*FieldList)(nil), "FieldList")
	proto.RegisterType((*InputValue)(nil), "InputValue")
	proto.RegisterType((*InputValueList)(nil), "InputValueList")
	proto.RegisterType((*Ident)(nil), "Ident")
	proto.RegisterType((*BasicLit)(nil), "BasicLit")
	proto.RegisterType((*CompositeLit)(nil), "CompositeLit")
	proto.RegisterType((*ListLit)(nil), "ListLit")
	proto.RegisterType((*ListLit_Basic)(nil), "ListLit.Basic")
	proto.RegisterType((*ListLit_Composite)(nil), "ListLit.Composite")
	proto.RegisterType((*ObjLit)(nil), "ObjLit")
	proto.RegisterType((*ObjLit_Pair)(nil), "ObjLit.Pair")
	proto.RegisterType((*List)(nil), "List")
	proto.RegisterType((*NonNull)(nil), "NonNull")
	proto.RegisterType((*DirectiveLit)(nil), "DirectiveLit")
	proto.RegisterType((*DirectiveLocation)(nil), "DirectiveLocation")
	proto.RegisterType((*CallExpr)(nil), "CallExpr")
	proto.RegisterType((*SchemaType)(nil), "SchemaType")
	proto.RegisterType((*ScalarType)(nil), "ScalarType")
	proto.RegisterType((*ObjectType)(nil), "ObjectType")
	proto.RegisterType((*InterfaceType)(nil), "InterfaceType")
	proto.RegisterType((*UnionType)(nil), "UnionType")
	proto.RegisterType((*EnumType)(nil), "EnumType")
	proto.RegisterType((*InputType)(nil), "InputType")
	proto.RegisterType((*DirectiveType)(nil), "DirectiveType")
	proto.RegisterType((*TypeSpec)(nil), "TypeSpec")
	proto.RegisterType((*TypeExtensionSpec)(nil), "TypeExtensionSpec")
	proto.RegisterType((*TypeDecl)(nil), "TypeDecl")
}

func init() { proto.RegisterFile("ast.proto", fileDescriptor_37b5b141da493253) }

var fileDescriptor_37b5b141da493253 = []byte{
	// 1565 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x58, 0x5f, 0x6f, 0xdb, 0x46,
	0x12, 0x17, 0x45, 0x91, 0x12, 0x47, 0xb6, 0xc3, 0x6c, 0x0c, 0x9f, 0xe0, 0x5c, 0xce, 0x0e, 0xcf,
	0x4e, 0x8c, 0x03, 0x8e, 0x0f, 0x0e, 0xee, 0x1e, 0xee, 0xe9, 0xf4, 0x87, 0xb6, 0x14, 0xc8, 0xb2,
	0xb3, 0x96, 0x52, 0x14, 0x7d, 0x30, 0x68, 0x9a, 0x71, 0x18, 0x53, 0x5c, 0x85, 0xa4, 0x8c, 0xe4,
	0x1b, 0x14, 0x7d, 0xea, 0x27, 0xe9, 0x73, 0xd1, 0xa2, 0xef, 0xfd, 0x12, 0x7d, 0xec, 0xe7, 0x68,
	0x31, 0xcb, 0x5d, 0x92, 0xb2, 0x1d, 0x39, 0x48, 0xdf, 0x76, 0x76, 0x66, 0x67, 0x67, 0x7e, 0xf3,
	0xdb, 0xe1, 0x48, 0x60, 0xb8, 0x49, 0x6a, 0xcf, 0x62, 0x96, 0x32, 0xeb, 0x07, 0x05, 0x1a, 0x3d,
	0xe6, 0xcd, 0xa7, 0x7e, 0x94, 0x12, 0x02, 0xb5, 0xc8, 0x9d, 0xfa, 0x2d, 0x65, 0x5b, 0xd9, 0x33,
	0x28, 0x5f, 0x93, 0xc7, 0xa0, 0x5e, 0x30, 0xaf, 0x55, 0xdd, 0x56, 0xf6, 0x9a, 0xfb, 0x86, 0xdd,
	0x63, 0xde, 0x61, 0xcc, 0xe6, 0x33, 0x8a, 0xbb, 0xe4, 0xdf, 0x00, 0x17, 0x41, 0xec, 0x7b, 0x69,
	0x70, 0xed, 0x27, 0x2d, 0x75, 0x5b, 0xdd, 0x6b, 0xee, 0xaf, 0xda, 0x3d, 0xb9, 0x35, 0x0c, 0x52,
	0x5a, 0x32, 0x20, 0x4f, 0x41, 0x4f, 0xbc, 0xb7, 0xfe, 0xd4, 0x6d, 0xd5, 0x84, 0xbb, 0xf1, 0xc7,
	0x99, 0xdf, 0xf3, 0xbd, 0x90, 0x0a, 0x05, 0xd9, 0x02, 0x2d, 0xfd, 0x38, 0xf3, 0x93, 0x96, 0xc6,
	0x9d, 0x95, 0x2c, 0xb2, 0x7d, 0xeb, 0x9a, 0xc7, 0xcb, 0x63, 0x20, 0x4f, 0xa1, 0x16, 0x06, 0x49,
	0xda, 0x52, 0xe4, 0xc5, 0x42, 0x81, 0x0b, 0xca, 0x55, 0x9b, 0x87, 0xa0, 0xf6, 0x98, 0x87, 0x99,
	0xa5, 0xfe, 0x87, 0x54, 0x66, 0x86, 0x6b, 0xdc, 0xf3, 0xde, 0xba, 0x31, 0x4f, 0x4d, 0xa5, 0x7c,
	0x4d, 0x5a, 0x50, 0xf7, 0xd8, 0x14, 0xc1, 0x68, 0xa9, 0xdb, 0xca, 0x5e, 0x83, 0x4a, 0xd1, 0xfa,
	0x56, 0x01, 0xb5, 0x1d, 0x5f, 0x92, 0xcd, 0x12, 0x46, 0xcd, 0x7d, 0xdd, 0x1e, 0x5c, 0xf8, 0x51,
	0x2a, 0xb0, 0x7a, 0x0e, 0x8d, 0x73, 0x37, 0x09, 0xbc, 0x61, 0x90, 0xe6, 0x80, 0x75, 0xc4, 0x46,
	0xbf, 0x42, 0x73, 0x25, 0x79, 0x01, 0x2b, 0x1e, 0x9b, 0xce, 0x58, 0x12, 0xa4, 0x08, 0x12, 0xbf,
	0x0b, 0x13, 0xe8, 0x96, 0x36, 0xfb, 0x15, 0xba, 0x60, 0xd4, 0xa9, 0x83, 0x76, 0xed, 0x86, 0x73,
	0xdf, 0xfa, 0x43, 0x01, 0xed, 0x20, 0xf0, 0xc3, 0x0b, 0x59, 0x1c, 0xe5, 0xce, 0xe2, 0xc8, 0x48,
	0xab, 0x77, 0x44, 0xfa, 0x4f, 0xa8, 0xb9, 0xf1, 0x65, 0x22, 0x2e, 0x7e, 0x60, 0x0f, 0xa2, 0xd9,
	0x3c, 0x7d, 0x8d, 0xde, 0x87, 0x41, 0x92, 0x52, 0xae, 0x24, 0xff, 0x00, 0x2d, 0xc0, 0x33, 0xa2,
	0x5a, 0xc2, 0x43, 0xbf, 0x42, 0xb3, 0x6d, 0xf2, 0x58, 0xc0, 0xaf, 0x71, 0xb5, 0x66, 0xe3, 0xd1,
	0x7e, 0x25, 0x03, 0x9e, 0xec, 0x40, 0x3d, 0x62, 0xd1, 0x68, 0x1e, 0x86, 0x2d, 0x9d, 0xeb, 0x1b,
	0xf6, 0x28, 0x93, 0xfb, 0x15, 0x2a, 0x55, 0x37, 0x08, 0x64, 0xdc, 0x43, 0xa0, 0x8e, 0x0e, 0x35,
	0x64, 0x81, 0xf5, 0x0d, 0x18, 0x1c, 0x00, 0xbc, 0x11, 0x6b, 0xc6, 0x66, 0x7e, 0x14, 0x44, 0x97,
	0x1c, 0x08, 0x95, 0x4a, 0x11, 0x11, 0xe0, 0x01, 0x56, 0xb9, 0x5f, 0xdd, 0xe6, 0x67, 0x44, 0x7c,
	0x58, 0xe9, 0x90, 0x25, 0x78, 0x4a, 0xcd, 0x4e, 0x09, 0xd1, 0xfa, 0xb5, 0x0a, 0x50, 0xe0, 0xf1,
	0xe5, 0x18, 0xe7, 0xf0, 0xa9, 0xcb, 0xe1, 0xab, 0xdd, 0x03, 0x9f, 0xf6, 0x69, 0xf8, 0xca, 0x84,
	0xd3, 0x6f, 0x12, 0x4e, 0x59, 0x42, 0xb8, 0xfa, 0x5d, 0x84, 0x53, 0x16, 0x09, 0xf7, 0x85, 0xc5,
	0xe9, 0x18, 0x50, 0xbf, 0xf0, 0xdf, 0xb8, 0xf3, 0x30, 0xb5, 0x7c, 0x58, 0x5b, 0x64, 0xd6, 0x92,
	0x62, 0x6d, 0x2d, 0x14, 0xab, 0x59, 0xa2, 0xe4, 0xbd, 0x15, 0xfb, 0x0f, 0x68, 0x1c, 0x5b, 0x34,
	0x41, 0xe8, 0x4f, 0x58, 0x22, 0xbd, 0x0b, 0x31, 0x6f, 0x6d, 0xd5, 0xa2, 0xb5, 0x59, 0x27, 0xd0,
	0x90, 0x60, 0x91, 0x4d, 0x68, 0xf0, 0xc7, 0x55, 0x1c, 0xcd, 0x65, 0x3c, 0x7b, 0x15, 0x44, 0x17,
	0xb2, 0x51, 0xe0, 0x9a, 0xac, 0x8b, 0xc7, 0xc8, 0x43, 0x31, 0xa8, 0x78, 0x99, 0xbf, 0x28, 0xb0,
	0x52, 0x86, 0x74, 0x49, 0xba, 0x9f, 0xdd, 0x2b, 0x76, 0xa0, 0x8e, 0xe9, 0x17, 0x6d, 0xa2, 0xc1,
	0x99, 0x92, 0x99, 0x49, 0x15, 0xb6, 0x56, 0x76, 0xfe, 0x0e, 0x8d, 0x32, 0x3a, 0xd5, 0xed, 0x63,
	0x2e, 0xf6, 0x2b, 0x54, 0x28, 0xca, 0xf8, 0x69, 0x0b, 0xf8, 0x15, 0x9d, 0xe5, 0x37, 0x05, 0xea,
	0xc2, 0x39, 0xb1, 0xc1, 0x10, 0x31, 0x24, 0xa9, 0x60, 0xff, 0x9a, 0xbc, 0x39, 0x8b, 0xb4, 0x5f,
	0xa1, 0x85, 0x09, 0xf9, 0x1f, 0xac, 0x96, 0xd8, 0x93, 0xc8, 0xac, 0x48, 0x7e, 0x26, 0x07, 0xa6,
	0x5f, 0xa1, 0x8b, 0xa6, 0x9b, 0xff, 0x02, 0x8d, 0x7b, 0xc4, 0x34, 0x78, 0x24, 0x89, 0xe8, 0xe9,
	0x05, 0x26, 0x54, 0x28, 0x36, 0xf7, 0xc1, 0xc8, 0x3d, 0x91, 0xdd, 0x1b, 0xf6, 0x8b, 0x8c, 0x96,
	0x67, 0x90, 0x9a, 0x08, 0x94, 0xf5, 0x1e, 0xf4, 0x0c, 0x16, 0xb2, 0x03, 0xfa, 0x1b, 0xec, 0x06,
	0xf2, 0xe0, 0x8a, 0xc0, 0xcb, 0x3e, 0x71, 0x83, 0x98, 0x0a, 0xdd, 0x66, 0x1b, 0x6a, 0x28, 0x93,
	0x16, 0xa8, 0x57, 0xfe, 0xc7, 0x1b, 0x3d, 0x1f, 0xb7, 0xc8, 0x16, 0xa8, 0xd7, 0x6e, 0x28, 0x72,
	0xbd, 0x71, 0x3b, 0x6a, 0xac, 0xf7, 0x50, 0xe3, 0xf0, 0xe4, 0xdd, 0x40, 0x59, 0xde, 0x0d, 0xaa,
	0xf7, 0x74, 0x03, 0xf5, 0x93, 0xdd, 0x20, 0xef, 0x8e, 0x23, 0xa8, 0x0b, 0xed, 0x5f, 0xba, 0x35,
	0xf7, 0xf7, 0x15, 0xac, 0x94, 0x1f, 0x3d, 0x72, 0xdf, 0x4d, 0x8b, 0x87, 0x92, 0x09, 0x77, 0xbd,
	0x30, 0xf2, 0x64, 0xe1, 0x33, 0x63, 0xd8, 0x5d, 0x37, 0x0c, 0x9d, 0x0f, 0xb3, 0x38, 0xfb, 0xc0,
	0x58, 0x3f, 0xab, 0xf0, 0xb0, 0xf0, 0xcc, 0x3c, 0x37, 0x0d, 0x58, 0x84, 0xee, 0x93, 0xd4, 0x8d,
	0x53, 0xe9, 0x9e, 0x0b, 0x64, 0x0f, 0xd4, 0x50, 0xcc, 0x21, 0x6b, 0xfb, 0x1b, 0xf6, 0xad, 0x63,
	0xf6, 0x90, 0x79, 0x14, 0x4d, 0xac, 0xdf, 0xab, 0xa0, 0x0e, 0x99, 0x47, 0x0c, 0xd0, 0x46, 0xec,
	0x84, 0x25, 0x66, 0x05, 0x97, 0xaf, 0x26, 0x0e, 0xfd, 0xda, 0x54, 0xc8, 0x0a, 0x34, 0x8e, 0x26,
	0xe3, 0xf6, 0x78, 0x70, 0x3c, 0x32, 0xab, 0xc4, 0x84, 0x95, 0xd3, 0x49, 0xe7, 0xb4, 0x4b, 0x07,
	0x27, 0x7c, 0x47, 0x45, 0xd3, 0x83, 0x81, 0x33, 0xec, 0x99, 0x35, 0xf2, 0x37, 0x78, 0x74, 0x40,
	0xdb, 0x87, 0x47, 0xce, 0x68, 0x7c, 0xd6, 0x73, 0x0e, 0x06, 0xa3, 0x01, 0xb7, 0xd1, 0xc8, 0x23,
	0x78, 0x90, 0x2b, 0x4e, 0x4f, 0xa8, 0xd3, 0xee, 0x99, 0x3a, 0x6e, 0x0e, 0x46, 0xc3, 0xc1, 0xc8,
	0x39, 0x93, 0x3a, 0xb3, 0x8e, 0x2e, 0x5e, 0xb7, 0xe9, 0xa0, 0xdd, 0x19, 0x3a, 0x65, 0x17, 0x0d,
	0x0c, 0xa3, 0x77, 0xdc, 0x9d, 0x70, 0x33, 0x83, 0x00, 0xe8, 0xa7, 0xdd, 0xbe, 0x73, 0xd4, 0x36,
	0x21, 0x5b, 0xb7, 0x87, 0x6d, 0x6a, 0x36, 0x71, 0x7d, 0xdc, 0x79, 0xe9, 0x74, 0xc7, 0xe6, 0x0a,
	0x59, 0x07, 0x93, 0x07, 0x56, 0xf6, 0xb3, 0x8a, 0x17, 0xb4, 0xe9, 0xe1, 0xe4, 0x66, 0x8c, 0x6b,
	0x64, 0x15, 0x8c, 0xc1, 0x68, 0xec, 0xd0, 0x83, 0x76, 0xd7, 0x31, 0x1f, 0x60, 0x5a, 0x93, 0x11,
	0x6a, 0x4c, 0xd2, 0x80, 0x9a, 0x33, 0x9a, 0x1c, 0x99, 0x0f, 0xc9, 0x1a, 0x00, 0xae, 0xce, 0x5e,
	0xb7, 0x87, 0x13, 0xc7, 0x24, 0x88, 0xc6, 0x60, 0x74, 0x32, 0x19, 0x9f, 0x89, 0x4b, 0x1f, 0x91,
	0x4d, 0xd8, 0xc8, 0x76, 0x6e, 0x5d, 0xbd, 0x6e, 0x8d, 0xa1, 0x21, 0xeb, 0x49, 0x36, 0x40, 0x0f,
	0x67, 0x6e, 0xec, 0x47, 0xa2, 0x68, 0x42, 0x22, 0x2d, 0x41, 0x80, 0xac, 0xa9, 0xd7, 0xec, 0x76,
	0x7c, 0x29, 0x86, 0x8b, 0x0d, 0xd0, 0xe3, 0xec, 0x44, 0xd6, 0xcc, 0x85, 0x64, 0xbd, 0x04, 0x38,
	0xe5, 0xa3, 0x20, 0x0e, 0x7e, 0x68, 0x25, 0x26, 0x46, 0xe1, 0x57, 0x8c, 0x89, 0x3b, 0x50, 0x8f,
	0x19, 0x4b, 0x8f, 0x67, 0x89, 0xa0, 0x2e, 0xd8, 0xf9, 0x40, 0x40, 0xa5, 0xca, 0xfa, 0x3f, 0xfa,
	0x72, 0x43, 0x37, 0x2e, 0x7c, 0xa1, 0x54, 0xf8, 0x42, 0x69, 0xd9, 0x37, 0xdc, 0xfa, 0x4e, 0x01,
	0x38, 0x3e, 0x7f, 0xe7, 0x7b, 0xa9, 0x74, 0xc1, 0xb8, 0x24, 0x5d, 0x64, 0x12, 0xb6, 0xd6, 0x60,
	0x3a, 0x0b, 0xf1, 0x4d, 0x64, 0x1f, 0x09, 0x29, 0x92, 0x67, 0x00, 0x41, 0x94, 0xfa, 0xf1, 0x1b,
	0xd7, 0xcb, 0x27, 0x64, 0x79, 0x45, 0x49, 0x43, 0xac, 0xbc, 0x1f, 0xd5, 0x6e, 0xe5, 0x23, 0x34,
	0xd6, 0x2b, 0x58, 0x1d, 0xc8, 0x13, 0x3c, 0x9c, 0xbf, 0x83, 0x91, 0xbb, 0x10, 0x11, 0x15, 0x1b,
	0x25, 0x97, 0xd5, 0x4f, 0xba, 0xec, 0x82, 0x31, 0x89, 0x02, 0x16, 0x71, 0x77, 0xeb, 0xa0, 0xcd,
	0x51, 0x90, 0x0f, 0x8f, 0x0b, 0x64, 0x1b, 0xea, 0x53, 0x7f, 0x7a, 0xee, 0xc7, 0x49, 0x3e, 0x47,
	0x65, 0xe1, 0xcb, 0x6d, 0xab, 0x03, 0x0d, 0x27, 0x9a, 0x4f, 0xb9, 0x0f, 0x02, 0x35, 0x3f, 0x9a,
	0x4f, 0x85, 0x0b, 0xbe, 0xc6, 0x40, 0x44, 0x93, 0xbe, 0x23, 0x90, 0x4c, 0x63, 0xbd, 0x04, 0x83,
	0x7f, 0xf0, 0x65, 0x20, 0x01, 0x0a, 0x32, 0x10, 0x2e, 0x90, 0xe7, 0x37, 0xf2, 0xb9, 0x35, 0xb5,
	0xca, 0xa4, 0xbe, 0x57, 0x60, 0x35, 0xef, 0x0f, 0x12, 0xa8, 0x7c, 0x50, 0x91, 0x40, 0xe5, 0x1b,
	0xf9, 0x30, 0x5c, 0x5d, 0x36, 0x0c, 0xaf, 0x83, 0xc6, 0x22, 0x2c, 0x70, 0x46, 0xd7, 0x4c, 0x20,
	0xcf, 0xa0, 0x16, 0x32, 0x0f, 0x8b, 0xa6, 0xf2, 0x6f, 0xdd, 0xad, 0xb6, 0x44, 0xb9, 0xde, 0xfa,
	0x51, 0x85, 0x06, 0x46, 0x72, 0x3a, 0xf3, 0xbd, 0x2f, 0x9f, 0x28, 0x77, 0xf3, 0xd7, 0x90, 0x35,
	0xd4, 0xa6, 0x5d, 0x3c, 0x15, 0xfc, 0xd0, 0x8b, 0xc7, 0xb1, 0x9b, 0x13, 0xbd, 0x96, 0x9b, 0xc9,
	0x57, 0x90, 0x99, 0x71, 0xde, 0xef, 0xe6, 0x64, 0xd6, 0x84, 0x59, 0xc1, 0x74, 0x31, 0x36, 0x20,
	0xb7, 0xed, 0x32, 0xc9, 0x74, 0x31, 0x07, 0x2c, 0xf0, 0x10, 0xe7, 0x80, 0x32, 0xed, 0x04, 0x8b,
	0xea, 0xa2, 0xd8, 0x39, 0xc1, 0xf0, 0xb3, 0x93, 0x71, 0x6a, 0x4b, 0xb0, 0xa4, 0x21, 0x20, 0x90,
	0xf4, 0xc1, 0x4f, 0x8f, 0xa0, 0x8c, 0x60, 0x80, 0x21, 0x9c, 0xe4, 0xe4, 0xe0, 0xdf, 0x2e, 0xce,
	0x07, 0xbb, 0x5c, 0x54, 0x10, 0x81, 0x2d, 0xd4, 0x1d, 0x03, 0x2b, 0xca, 0xbc, 0x38, 0xce, 0x36,
	0x3f, 0xf7, 0xb7, 0xc6, 0x31, 0x3c, 0x44, 0x5f, 0xce, 0x87, 0xd4, 0x8f, 0x92, 0x80, 0x45, 0xf7,
	0x97, 0xf0, 0x49, 0x76, 0x32, 0x1f, 0xeb, 0x64, 0xe1, 0x69, 0xe6, 0xf0, 0x27, 0x25, 0xe3, 0x02,
	0xfe, 0xaa, 0x5d, 0xee, 0x68, 0x03, 0xf4, 0x94, 0x5d, 0x15, 0x5d, 0x45, 0x48, 0xc4, 0x04, 0x35,
	0x65, 0x57, 0x82, 0x89, 0xb8, 0xc4, 0x69, 0x32, 0x15, 0xb7, 0x2c, 0xfc, 0xb6, 0xc6, 0x0d, 0x9c,
	0x26, 0xa5, 0x92, 0xfc, 0x17, 0x9a, 0x69, 0x96, 0x0d, 0xb7, 0xd5, 0xc4, 0x8c, 0x76, 0x2b, 0xc3,
	0x7e, 0x85, 0x96, 0x0d, 0x11, 0x8d, 0x64, 0xe6, 0x7b, 0xe7, 0x3a, 0xff, 0xdb, 0xe0, 0xc5, 0x9f,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x88, 0x30, 0xda, 0xc2, 0x43, 0x10, 0x00, 0x00,
}
