// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ast.proto

package ast

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DirectiveLocation_Loc int32

const (
	DirectiveLocation_NoPos DirectiveLocation_Loc = 0
	// ExecutableDirectiveLocations
	DirectiveLocation_Query               DirectiveLocation_Loc = 1
	DirectiveLocation_MUTATION            DirectiveLocation_Loc = 2
	DirectiveLocation_SUBSCRIPTION        DirectiveLocation_Loc = 3
	DirectiveLocation_FIELD               DirectiveLocation_Loc = 4
	DirectiveLocation_FRAGMENT_DEFINITION DirectiveLocation_Loc = 5
	DirectiveLocation_FRAGMENT_SPREAD     DirectiveLocation_Loc = 6
	DirectiveLocation_INLINE_FRAGMENT     DirectiveLocation_Loc = 7
	DirectiveLocation_VARIABLE_DEFINITION DirectiveLocation_Loc = 8
	// TypeSystemDirectiveLocations
	DirectiveLocation_DOCUMENT               DirectiveLocation_Loc = 9
	DirectiveLocation_SCHEMA                 DirectiveLocation_Loc = 10
	DirectiveLocation_SCALAR                 DirectiveLocation_Loc = 11
	DirectiveLocation_OBJECT                 DirectiveLocation_Loc = 12
	DirectiveLocation_FIELD_DEFINITION       DirectiveLocation_Loc = 13
	DirectiveLocation_ARGUMENT_DEFINITION    DirectiveLocation_Loc = 14
	DirectiveLocation_INTERFACE              DirectiveLocation_Loc = 15
	DirectiveLocation_UNION                  DirectiveLocation_Loc = 16
	DirectiveLocation_ENUM                   DirectiveLocation_Loc = 17
	DirectiveLocation_ENUM_VALUE             DirectiveLocation_Loc = 18
	DirectiveLocation_INPUT_OBJECT           DirectiveLocation_Loc = 19
	DirectiveLocation_INPUT_FIELD_DEFINITION DirectiveLocation_Loc = 20
)

var DirectiveLocation_Loc_name = map[int32]string{
	0:  "NoPos",
	1:  "Query",
	2:  "MUTATION",
	3:  "SUBSCRIPTION",
	4:  "FIELD",
	5:  "FRAGMENT_DEFINITION",
	6:  "FRAGMENT_SPREAD",
	7:  "INLINE_FRAGMENT",
	8:  "VARIABLE_DEFINITION",
	9:  "DOCUMENT",
	10: "SCHEMA",
	11: "SCALAR",
	12: "OBJECT",
	13: "FIELD_DEFINITION",
	14: "ARGUMENT_DEFINITION",
	15: "INTERFACE",
	16: "UNION",
	17: "ENUM",
	18: "ENUM_VALUE",
	19: "INPUT_OBJECT",
	20: "INPUT_FIELD_DEFINITION",
}

var DirectiveLocation_Loc_value = map[string]int32{
	"NoPos":                  0,
	"Query":                  1,
	"MUTATION":               2,
	"SUBSCRIPTION":           3,
	"FIELD":                  4,
	"FRAGMENT_DEFINITION":    5,
	"FRAGMENT_SPREAD":        6,
	"INLINE_FRAGMENT":        7,
	"VARIABLE_DEFINITION":    8,
	"DOCUMENT":               9,
	"SCHEMA":                 10,
	"SCALAR":                 11,
	"OBJECT":                 12,
	"FIELD_DEFINITION":       13,
	"ARGUMENT_DEFINITION":    14,
	"INTERFACE":              15,
	"UNION":                  16,
	"ENUM":                   17,
	"ENUM_VALUE":             18,
	"INPUT_OBJECT":           19,
	"INPUT_FIELD_DEFINITION": 20,
}

func (x DirectiveLocation_Loc) String() string {
	return proto.EnumName(DirectiveLocation_Loc_name, int32(x))
}

func (DirectiveLocation_Loc) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_37b5b141da493253, []int{12, 0}
}

// Describes a complete GraphQL Document.
type Document struct {
	// file name, relative to root of source tree.
	Name string    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Doc  *DocGroup `protobuf:"bytes,2,opt,name=doc,proto3" json:"doc,omitempty"`
	// All top-level directives.
	Directives []*DirectiveLit `protobuf:"bytes,3,rep,name=directives,proto3" json:"directives,omitempty"`
	// All top-level definitions in this file.
	Schema               *TypeDecl   `protobuf:"bytes,4,opt,name=schema,proto3" json:"schema,omitempty"`
	Types                []*TypeDecl `protobuf:"bytes,5,rep,name=types,proto3" json:"types,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Document) Reset()         { *m = Document{} }
func (m *Document) String() string { return proto.CompactTextString(m) }
func (*Document) ProtoMessage()    {}
func (*Document) Descriptor() ([]byte, []int) {
	return fileDescriptor_37b5b141da493253, []int{0}
}

func (m *Document) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Document.Unmarshal(m, b)
}
func (m *Document) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Document.Marshal(b, m, deterministic)
}
func (m *Document) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Document.Merge(m, src)
}
func (m *Document) XXX_Size() int {
	return xxx_messageInfo_Document.Size(m)
}
func (m *Document) XXX_DiscardUnknown() {
	xxx_messageInfo_Document.DiscardUnknown(m)
}

var xxx_messageInfo_Document proto.InternalMessageInfo

func (m *Document) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Document) GetDoc() *DocGroup {
	if m != nil {
		return m.Doc
	}
	return nil
}

func (m *Document) GetDirectives() []*DirectiveLit {
	if m != nil {
		return m.Directives
	}
	return nil
}

func (m *Document) GetSchema() *TypeDecl {
	if m != nil {
		return m.Schema
	}
	return nil
}

func (m *Document) GetTypes() []*TypeDecl {
	if m != nil {
		return m.Types
	}
	return nil
}

type DocGroup struct {
	List                 []*DocGroup_Doc `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *DocGroup) Reset()         { *m = DocGroup{} }
func (m *DocGroup) String() string { return proto.CompactTextString(m) }
func (*DocGroup) ProtoMessage()    {}
func (*DocGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_37b5b141da493253, []int{1}
}

func (m *DocGroup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DocGroup.Unmarshal(m, b)
}
func (m *DocGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DocGroup.Marshal(b, m, deterministic)
}
func (m *DocGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DocGroup.Merge(m, src)
}
func (m *DocGroup) XXX_Size() int {
	return xxx_messageInfo_DocGroup.Size(m)
}
func (m *DocGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_DocGroup.DiscardUnknown(m)
}

var xxx_messageInfo_DocGroup proto.InternalMessageInfo

func (m *DocGroup) GetList() []*DocGroup_Doc {
	if m != nil {
		return m.List
	}
	return nil
}

type DocGroup_Doc struct {
	Text                 string   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Char                 int64    `protobuf:"varint,2,opt,name=char,proto3" json:"char,omitempty"`
	Comment              bool     `protobuf:"varint,3,opt,name=comment,proto3" json:"comment,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DocGroup_Doc) Reset()         { *m = DocGroup_Doc{} }
func (m *DocGroup_Doc) String() string { return proto.CompactTextString(m) }
func (*DocGroup_Doc) ProtoMessage()    {}
func (*DocGroup_Doc) Descriptor() ([]byte, []int) {
	return fileDescriptor_37b5b141da493253, []int{1, 0}
}

func (m *DocGroup_Doc) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DocGroup_Doc.Unmarshal(m, b)
}
func (m *DocGroup_Doc) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DocGroup_Doc.Marshal(b, m, deterministic)
}
func (m *DocGroup_Doc) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DocGroup_Doc.Merge(m, src)
}
func (m *DocGroup_Doc) XXX_Size() int {
	return xxx_messageInfo_DocGroup_Doc.Size(m)
}
func (m *DocGroup_Doc) XXX_DiscardUnknown() {
	xxx_messageInfo_DocGroup_Doc.DiscardUnknown(m)
}

var xxx_messageInfo_DocGroup_Doc proto.InternalMessageInfo

func (m *DocGroup_Doc) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *DocGroup_Doc) GetChar() int64 {
	if m != nil {
		return m.Char
	}
	return 0
}

func (m *DocGroup_Doc) GetComment() bool {
	if m != nil {
		return m.Comment
	}
	return false
}

// A Arg represents an Argument pair in a applied directive.
type Arg struct {
	Name *Ident `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Types that are valid to be assigned to Value:
	//	*Arg_Blit
	//	*Arg_Llit
	//	*Arg_Olit
	Value                isArg_Value `protobuf_oneof:"value"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Arg) Reset()         { *m = Arg{} }
func (m *Arg) String() string { return proto.CompactTextString(m) }
func (*Arg) ProtoMessage()    {}
func (*Arg) Descriptor() ([]byte, []int) {
	return fileDescriptor_37b5b141da493253, []int{2}
}

func (m *Arg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Arg.Unmarshal(m, b)
}
func (m *Arg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Arg.Marshal(b, m, deterministic)
}
func (m *Arg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Arg.Merge(m, src)
}
func (m *Arg) XXX_Size() int {
	return xxx_messageInfo_Arg.Size(m)
}
func (m *Arg) XXX_DiscardUnknown() {
	xxx_messageInfo_Arg.DiscardUnknown(m)
}

var xxx_messageInfo_Arg proto.InternalMessageInfo

func (m *Arg) GetName() *Ident {
	if m != nil {
		return m.Name
	}
	return nil
}

type isArg_Value interface {
	isArg_Value()
}

type Arg_Blit struct {
	Blit *BasicLit `protobuf:"bytes,2,opt,name=blit,proto3,oneof"`
}

type Arg_Llit struct {
	Llit *ListLit `protobuf:"bytes,3,opt,name=llit,proto3,oneof"`
}

type Arg_Olit struct {
	Olit *ObjLit `protobuf:"bytes,4,opt,name=olit,proto3,oneof"`
}

func (*Arg_Blit) isArg_Value() {}

func (*Arg_Llit) isArg_Value() {}

func (*Arg_Olit) isArg_Value() {}

func (m *Arg) GetValue() isArg_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Arg) GetBlit() *BasicLit {
	if x, ok := m.GetValue().(*Arg_Blit); ok {
		return x.Blit
	}
	return nil
}

func (m *Arg) GetLlit() *ListLit {
	if x, ok := m.GetValue().(*Arg_Llit); ok {
		return x.Llit
	}
	return nil
}

func (m *Arg) GetOlit() *ObjLit {
	if x, ok := m.GetValue().(*Arg_Olit); ok {
		return x.Olit
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Arg) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Arg_Blit)(nil),
		(*Arg_Llit)(nil),
		(*Arg_Olit)(nil),
	}
}

// A Field represents a Field declaration in a GraphQL type declaration
// or an argument declaration in an arguments declaration.
//
type Field struct {
	Doc  *DocGroup  `protobuf:"bytes,1,opt,name=doc,proto3" json:"doc,omitempty"`
	Name *Ident     `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Args *FieldList `protobuf:"bytes,3,opt,name=args,proto3" json:"args,omitempty"`
	// field/parameter type
	//
	// Types that are valid to be assigned to Type:
	//	*Field_Ident
	//	*Field_List
	//	*Field_NonNull
	Type isField_Type `protobuf_oneof:"type"`
	// parameter default value; or nil
	//
	// Types that are valid to be assigned to Default:
	//	*Field_Blit
	//	*Field_Llit
	//	*Field_Olit
	Default              isField_Default `protobuf_oneof:"default"`
	Directives           []*DirectiveLit `protobuf:"bytes,10,rep,name=directives,proto3" json:"directives,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Field) Reset()         { *m = Field{} }
func (m *Field) String() string { return proto.CompactTextString(m) }
func (*Field) ProtoMessage()    {}
func (*Field) Descriptor() ([]byte, []int) {
	return fileDescriptor_37b5b141da493253, []int{3}
}

func (m *Field) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Field.Unmarshal(m, b)
}
func (m *Field) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Field.Marshal(b, m, deterministic)
}
func (m *Field) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Field.Merge(m, src)
}
func (m *Field) XXX_Size() int {
	return xxx_messageInfo_Field.Size(m)
}
func (m *Field) XXX_DiscardUnknown() {
	xxx_messageInfo_Field.DiscardUnknown(m)
}

var xxx_messageInfo_Field proto.InternalMessageInfo

func (m *Field) GetDoc() *DocGroup {
	if m != nil {
		return m.Doc
	}
	return nil
}

func (m *Field) GetName() *Ident {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *Field) GetArgs() *FieldList {
	if m != nil {
		return m.Args
	}
	return nil
}

type isField_Type interface {
	isField_Type()
}

type Field_Ident struct {
	Ident *Ident `protobuf:"bytes,4,opt,name=ident,proto3,oneof"`
}

type Field_List struct {
	List *List `protobuf:"bytes,5,opt,name=list,proto3,oneof"`
}

type Field_NonNull struct {
	NonNull *NonNull `protobuf:"bytes,6,opt,name=nonNull,proto3,oneof"`
}

func (*Field_Ident) isField_Type() {}

func (*Field_List) isField_Type() {}

func (*Field_NonNull) isField_Type() {}

func (m *Field) GetType() isField_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *Field) GetIdent() *Ident {
	if x, ok := m.GetType().(*Field_Ident); ok {
		return x.Ident
	}
	return nil
}

func (m *Field) GetList() *List {
	if x, ok := m.GetType().(*Field_List); ok {
		return x.List
	}
	return nil
}

func (m *Field) GetNonNull() *NonNull {
	if x, ok := m.GetType().(*Field_NonNull); ok {
		return x.NonNull
	}
	return nil
}

type isField_Default interface {
	isField_Default()
}

type Field_Blit struct {
	Blit *BasicLit `protobuf:"bytes,7,opt,name=blit,proto3,oneof"`
}

type Field_Llit struct {
	Llit *ListLit `protobuf:"bytes,8,opt,name=llit,proto3,oneof"`
}

type Field_Olit struct {
	Olit *ObjLit `protobuf:"bytes,9,opt,name=olit,proto3,oneof"`
}

func (*Field_Blit) isField_Default() {}

func (*Field_Llit) isField_Default() {}

func (*Field_Olit) isField_Default() {}

func (m *Field) GetDefault() isField_Default {
	if m != nil {
		return m.Default
	}
	return nil
}

func (m *Field) GetBlit() *BasicLit {
	if x, ok := m.GetDefault().(*Field_Blit); ok {
		return x.Blit
	}
	return nil
}

func (m *Field) GetLlit() *ListLit {
	if x, ok := m.GetDefault().(*Field_Llit); ok {
		return x.Llit
	}
	return nil
}

func (m *Field) GetOlit() *ObjLit {
	if x, ok := m.GetDefault().(*Field_Olit); ok {
		return x.Olit
	}
	return nil
}

func (m *Field) GetDirectives() []*DirectiveLit {
	if m != nil {
		return m.Directives
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Field) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Field_Ident)(nil),
		(*Field_List)(nil),
		(*Field_NonNull)(nil),
		(*Field_Blit)(nil),
		(*Field_Llit)(nil),
		(*Field_Olit)(nil),
	}
}

// A FieldList represents a list of Fields, enclosed by parentheses or braces.
type FieldList struct {
	Opening              int64    `protobuf:"varint,1,opt,name=opening,proto3" json:"opening,omitempty"`
	List                 []*Field `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	Closing              int64    `protobuf:"varint,3,opt,name=closing,proto3" json:"closing,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FieldList) Reset()         { *m = FieldList{} }
func (m *FieldList) String() string { return proto.CompactTextString(m) }
func (*FieldList) ProtoMessage()    {}
func (*FieldList) Descriptor() ([]byte, []int) {
	return fileDescriptor_37b5b141da493253, []int{4}
}

func (m *FieldList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FieldList.Unmarshal(m, b)
}
func (m *FieldList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FieldList.Marshal(b, m, deterministic)
}
func (m *FieldList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FieldList.Merge(m, src)
}
func (m *FieldList) XXX_Size() int {
	return xxx_messageInfo_FieldList.Size(m)
}
func (m *FieldList) XXX_DiscardUnknown() {
	xxx_messageInfo_FieldList.DiscardUnknown(m)
}

var xxx_messageInfo_FieldList proto.InternalMessageInfo

func (m *FieldList) GetOpening() int64 {
	if m != nil {
		return m.Opening
	}
	return 0
}

func (m *FieldList) GetList() []*Field {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *FieldList) GetClosing() int64 {
	if m != nil {
		return m.Closing
	}
	return 0
}

// Ident represents an identifier.
type Ident struct {
	NamePos              int64    `protobuf:"varint,1,opt,name=namePos,proto3" json:"namePos,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ident) Reset()         { *m = Ident{} }
func (m *Ident) String() string { return proto.CompactTextString(m) }
func (*Ident) ProtoMessage()    {}
func (*Ident) Descriptor() ([]byte, []int) {
	return fileDescriptor_37b5b141da493253, []int{5}
}

func (m *Ident) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ident.Unmarshal(m, b)
}
func (m *Ident) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ident.Marshal(b, m, deterministic)
}
func (m *Ident) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ident.Merge(m, src)
}
func (m *Ident) XXX_Size() int {
	return xxx_messageInfo_Ident.Size(m)
}
func (m *Ident) XXX_DiscardUnknown() {
	xxx_messageInfo_Ident.DiscardUnknown(m)
}

var xxx_messageInfo_Ident proto.InternalMessageInfo

func (m *Ident) GetNamePos() int64 {
	if m != nil {
		return m.NamePos
	}
	return 0
}

func (m *Ident) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// BasicLit represents a literal of basic type.
type BasicLit struct {
	ValuePos             int64    `protobuf:"varint,1,opt,name=valuePos,proto3" json:"valuePos,omitempty"`
	Kind                 int64    `protobuf:"varint,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Value                string   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BasicLit) Reset()         { *m = BasicLit{} }
func (m *BasicLit) String() string { return proto.CompactTextString(m) }
func (*BasicLit) ProtoMessage()    {}
func (*BasicLit) Descriptor() ([]byte, []int) {
	return fileDescriptor_37b5b141da493253, []int{6}
}

func (m *BasicLit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BasicLit.Unmarshal(m, b)
}
func (m *BasicLit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BasicLit.Marshal(b, m, deterministic)
}
func (m *BasicLit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BasicLit.Merge(m, src)
}
func (m *BasicLit) XXX_Size() int {
	return xxx_messageInfo_BasicLit.Size(m)
}
func (m *BasicLit) XXX_DiscardUnknown() {
	xxx_messageInfo_BasicLit.DiscardUnknown(m)
}

var xxx_messageInfo_BasicLit proto.InternalMessageInfo

func (m *BasicLit) GetValuePos() int64 {
	if m != nil {
		return m.ValuePos
	}
	return 0
}

func (m *BasicLit) GetKind() int64 {
	if m != nil {
		return m.Kind
	}
	return 0
}

func (m *BasicLit) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// TODO: ListLit represents a list literal value.
type ListLit struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListLit) Reset()         { *m = ListLit{} }
func (m *ListLit) String() string { return proto.CompactTextString(m) }
func (*ListLit) ProtoMessage()    {}
func (*ListLit) Descriptor() ([]byte, []int) {
	return fileDescriptor_37b5b141da493253, []int{7}
}

func (m *ListLit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListLit.Unmarshal(m, b)
}
func (m *ListLit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListLit.Marshal(b, m, deterministic)
}
func (m *ListLit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListLit.Merge(m, src)
}
func (m *ListLit) XXX_Size() int {
	return xxx_messageInfo_ListLit.Size(m)
}
func (m *ListLit) XXX_DiscardUnknown() {
	xxx_messageInfo_ListLit.DiscardUnknown(m)
}

var xxx_messageInfo_ListLit proto.InternalMessageInfo

// TODO: ObjLit represents an object literal value.
type ObjLit struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ObjLit) Reset()         { *m = ObjLit{} }
func (m *ObjLit) String() string { return proto.CompactTextString(m) }
func (*ObjLit) ProtoMessage()    {}
func (*ObjLit) Descriptor() ([]byte, []int) {
	return fileDescriptor_37b5b141da493253, []int{8}
}

func (m *ObjLit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObjLit.Unmarshal(m, b)
}
func (m *ObjLit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObjLit.Marshal(b, m, deterministic)
}
func (m *ObjLit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjLit.Merge(m, src)
}
func (m *ObjLit) XXX_Size() int {
	return xxx_messageInfo_ObjLit.Size(m)
}
func (m *ObjLit) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjLit.DiscardUnknown(m)
}

var xxx_messageInfo_ObjLit proto.InternalMessageInfo

// List represents a List type.
type List struct {
	// Types that are valid to be assigned to Type:
	//	*List_Ident
	//	*List_List
	//	*List_NonNull
	Type                 isList_Type `protobuf_oneof:"type"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *List) Reset()         { *m = List{} }
func (m *List) String() string { return proto.CompactTextString(m) }
func (*List) ProtoMessage()    {}
func (*List) Descriptor() ([]byte, []int) {
	return fileDescriptor_37b5b141da493253, []int{9}
}

func (m *List) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_List.Unmarshal(m, b)
}
func (m *List) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_List.Marshal(b, m, deterministic)
}
func (m *List) XXX_Merge(src proto.Message) {
	xxx_messageInfo_List.Merge(m, src)
}
func (m *List) XXX_Size() int {
	return xxx_messageInfo_List.Size(m)
}
func (m *List) XXX_DiscardUnknown() {
	xxx_messageInfo_List.DiscardUnknown(m)
}

var xxx_messageInfo_List proto.InternalMessageInfo

type isList_Type interface {
	isList_Type()
}

type List_Ident struct {
	Ident *Ident `protobuf:"bytes,1,opt,name=ident,proto3,oneof"`
}

type List_List struct {
	List *List `protobuf:"bytes,2,opt,name=list,proto3,oneof"`
}

type List_NonNull struct {
	NonNull *NonNull `protobuf:"bytes,3,opt,name=nonNull,proto3,oneof"`
}

func (*List_Ident) isList_Type() {}

func (*List_List) isList_Type() {}

func (*List_NonNull) isList_Type() {}

func (m *List) GetType() isList_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *List) GetIdent() *Ident {
	if x, ok := m.GetType().(*List_Ident); ok {
		return x.Ident
	}
	return nil
}

func (m *List) GetList() *List {
	if x, ok := m.GetType().(*List_List); ok {
		return x.List
	}
	return nil
}

func (m *List) GetNonNull() *NonNull {
	if x, ok := m.GetType().(*List_NonNull); ok {
		return x.NonNull
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*List) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*List_Ident)(nil),
		(*List_List)(nil),
		(*List_NonNull)(nil),
	}
}

// NonNull represents an identifier with the non-null character, '!', after it.
type NonNull struct {
	// Types that are valid to be assigned to Type:
	//	*NonNull_Ident
	//	*NonNull_List
	Type                 isNonNull_Type `protobuf_oneof:"type"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *NonNull) Reset()         { *m = NonNull{} }
func (m *NonNull) String() string { return proto.CompactTextString(m) }
func (*NonNull) ProtoMessage()    {}
func (*NonNull) Descriptor() ([]byte, []int) {
	return fileDescriptor_37b5b141da493253, []int{10}
}

func (m *NonNull) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NonNull.Unmarshal(m, b)
}
func (m *NonNull) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NonNull.Marshal(b, m, deterministic)
}
func (m *NonNull) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NonNull.Merge(m, src)
}
func (m *NonNull) XXX_Size() int {
	return xxx_messageInfo_NonNull.Size(m)
}
func (m *NonNull) XXX_DiscardUnknown() {
	xxx_messageInfo_NonNull.DiscardUnknown(m)
}

var xxx_messageInfo_NonNull proto.InternalMessageInfo

type isNonNull_Type interface {
	isNonNull_Type()
}

type NonNull_Ident struct {
	Ident *Ident `protobuf:"bytes,1,opt,name=ident,proto3,oneof"`
}

type NonNull_List struct {
	List *List `protobuf:"bytes,2,opt,name=list,proto3,oneof"`
}

func (*NonNull_Ident) isNonNull_Type() {}

func (*NonNull_List) isNonNull_Type() {}

func (m *NonNull) GetType() isNonNull_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *NonNull) GetIdent() *Ident {
	if x, ok := m.GetType().(*NonNull_Ident); ok {
		return x.Ident
	}
	return nil
}

func (m *NonNull) GetList() *List {
	if x, ok := m.GetType().(*NonNull_List); ok {
		return x.List
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*NonNull) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*NonNull_Ident)(nil),
		(*NonNull_List)(nil),
	}
}

// DirectiveLit presents an applied directive
type DirectiveLit struct {
	AtPos                int64     `protobuf:"varint,1,opt,name=atPos,proto3" json:"atPos,omitempty"`
	Name                 string    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Args                 *CallExpr `protobuf:"bytes,3,opt,name=args,proto3" json:"args,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *DirectiveLit) Reset()         { *m = DirectiveLit{} }
func (m *DirectiveLit) String() string { return proto.CompactTextString(m) }
func (*DirectiveLit) ProtoMessage()    {}
func (*DirectiveLit) Descriptor() ([]byte, []int) {
	return fileDescriptor_37b5b141da493253, []int{11}
}

func (m *DirectiveLit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DirectiveLit.Unmarshal(m, b)
}
func (m *DirectiveLit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DirectiveLit.Marshal(b, m, deterministic)
}
func (m *DirectiveLit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DirectiveLit.Merge(m, src)
}
func (m *DirectiveLit) XXX_Size() int {
	return xxx_messageInfo_DirectiveLit.Size(m)
}
func (m *DirectiveLit) XXX_DiscardUnknown() {
	xxx_messageInfo_DirectiveLit.DiscardUnknown(m)
}

var xxx_messageInfo_DirectiveLit proto.InternalMessageInfo

func (m *DirectiveLit) GetAtPos() int64 {
	if m != nil {
		return m.AtPos
	}
	return 0
}

func (m *DirectiveLit) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DirectiveLit) GetArgs() *CallExpr {
	if m != nil {
		return m.Args
	}
	return nil
}

// DirectiveLocation represents a defined directive location in a directive declaration.
type DirectiveLocation struct {
	Start                int64                 `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"`
	Loc                  DirectiveLocation_Loc `protobuf:"varint,2,opt,name=loc,proto3,enum=DirectiveLocation_Loc" json:"loc,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *DirectiveLocation) Reset()         { *m = DirectiveLocation{} }
func (m *DirectiveLocation) String() string { return proto.CompactTextString(m) }
func (*DirectiveLocation) ProtoMessage()    {}
func (*DirectiveLocation) Descriptor() ([]byte, []int) {
	return fileDescriptor_37b5b141da493253, []int{12}
}

func (m *DirectiveLocation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DirectiveLocation.Unmarshal(m, b)
}
func (m *DirectiveLocation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DirectiveLocation.Marshal(b, m, deterministic)
}
func (m *DirectiveLocation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DirectiveLocation.Merge(m, src)
}
func (m *DirectiveLocation) XXX_Size() int {
	return xxx_messageInfo_DirectiveLocation.Size(m)
}
func (m *DirectiveLocation) XXX_DiscardUnknown() {
	xxx_messageInfo_DirectiveLocation.DiscardUnknown(m)
}

var xxx_messageInfo_DirectiveLocation proto.InternalMessageInfo

func (m *DirectiveLocation) GetStart() int64 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *DirectiveLocation) GetLoc() DirectiveLocation_Loc {
	if m != nil {
		return m.Loc
	}
	return DirectiveLocation_NoPos
}

// CallExpr represents an expression followed by an argument list.
type CallExpr struct {
	Lparen               int64    `protobuf:"varint,1,opt,name=lparen,proto3" json:"lparen,omitempty"`
	Args                 []*Arg   `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	Rparen               int64    `protobuf:"varint,3,opt,name=rparen,proto3" json:"rparen,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CallExpr) Reset()         { *m = CallExpr{} }
func (m *CallExpr) String() string { return proto.CompactTextString(m) }
func (*CallExpr) ProtoMessage()    {}
func (*CallExpr) Descriptor() ([]byte, []int) {
	return fileDescriptor_37b5b141da493253, []int{13}
}

func (m *CallExpr) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CallExpr.Unmarshal(m, b)
}
func (m *CallExpr) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CallExpr.Marshal(b, m, deterministic)
}
func (m *CallExpr) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CallExpr.Merge(m, src)
}
func (m *CallExpr) XXX_Size() int {
	return xxx_messageInfo_CallExpr.Size(m)
}
func (m *CallExpr) XXX_DiscardUnknown() {
	xxx_messageInfo_CallExpr.DiscardUnknown(m)
}

var xxx_messageInfo_CallExpr proto.InternalMessageInfo

func (m *CallExpr) GetLparen() int64 {
	if m != nil {
		return m.Lparen
	}
	return 0
}

func (m *CallExpr) GetArgs() []*Arg {
	if m != nil {
		return m.Args
	}
	return nil
}

func (m *CallExpr) GetRparen() int64 {
	if m != nil {
		return m.Rparen
	}
	return 0
}

// SchemaType represents a schema type declaration.
type SchemaType struct {
	Schema               int64      `protobuf:"varint,1,opt,name=schema,proto3" json:"schema,omitempty"`
	RootOps              *FieldList `protobuf:"bytes,2,opt,name=rootOps,proto3" json:"rootOps,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SchemaType) Reset()         { *m = SchemaType{} }
func (m *SchemaType) String() string { return proto.CompactTextString(m) }
func (*SchemaType) ProtoMessage()    {}
func (*SchemaType) Descriptor() ([]byte, []int) {
	return fileDescriptor_37b5b141da493253, []int{14}
}

func (m *SchemaType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SchemaType.Unmarshal(m, b)
}
func (m *SchemaType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SchemaType.Marshal(b, m, deterministic)
}
func (m *SchemaType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SchemaType.Merge(m, src)
}
func (m *SchemaType) XXX_Size() int {
	return xxx_messageInfo_SchemaType.Size(m)
}
func (m *SchemaType) XXX_DiscardUnknown() {
	xxx_messageInfo_SchemaType.DiscardUnknown(m)
}

var xxx_messageInfo_SchemaType proto.InternalMessageInfo

func (m *SchemaType) GetSchema() int64 {
	if m != nil {
		return m.Schema
	}
	return 0
}

func (m *SchemaType) GetRootOps() *FieldList {
	if m != nil {
		return m.RootOps
	}
	return nil
}

// ScalarType represents a scalar type declaration.
type ScalarType struct {
	Scalar               int64    `protobuf:"varint,1,opt,name=scalar,proto3" json:"scalar,omitempty"`
	Name                 *Ident   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ScalarType) Reset()         { *m = ScalarType{} }
func (m *ScalarType) String() string { return proto.CompactTextString(m) }
func (*ScalarType) ProtoMessage()    {}
func (*ScalarType) Descriptor() ([]byte, []int) {
	return fileDescriptor_37b5b141da493253, []int{15}
}

func (m *ScalarType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScalarType.Unmarshal(m, b)
}
func (m *ScalarType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScalarType.Marshal(b, m, deterministic)
}
func (m *ScalarType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScalarType.Merge(m, src)
}
func (m *ScalarType) XXX_Size() int {
	return xxx_messageInfo_ScalarType.Size(m)
}
func (m *ScalarType) XXX_DiscardUnknown() {
	xxx_messageInfo_ScalarType.DiscardUnknown(m)
}

var xxx_messageInfo_ScalarType proto.InternalMessageInfo

func (m *ScalarType) GetScalar() int64 {
	if m != nil {
		return m.Scalar
	}
	return 0
}

func (m *ScalarType) GetName() *Ident {
	if m != nil {
		return m.Name
	}
	return nil
}

// ObjectType represents an object type declaration.
type ObjectType struct {
	Object               int64      `protobuf:"varint,1,opt,name=object,proto3" json:"object,omitempty"`
	ImplPos              int64      `protobuf:"varint,2,opt,name=implPos,proto3" json:"implPos,omitempty"`
	Interfaces           []*Ident   `protobuf:"bytes,3,rep,name=interfaces,proto3" json:"interfaces,omitempty"`
	Fields               *FieldList `protobuf:"bytes,4,opt,name=fields,proto3" json:"fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ObjectType) Reset()         { *m = ObjectType{} }
func (m *ObjectType) String() string { return proto.CompactTextString(m) }
func (*ObjectType) ProtoMessage()    {}
func (*ObjectType) Descriptor() ([]byte, []int) {
	return fileDescriptor_37b5b141da493253, []int{16}
}

func (m *ObjectType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObjectType.Unmarshal(m, b)
}
func (m *ObjectType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObjectType.Marshal(b, m, deterministic)
}
func (m *ObjectType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjectType.Merge(m, src)
}
func (m *ObjectType) XXX_Size() int {
	return xxx_messageInfo_ObjectType.Size(m)
}
func (m *ObjectType) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjectType.DiscardUnknown(m)
}

var xxx_messageInfo_ObjectType proto.InternalMessageInfo

func (m *ObjectType) GetObject() int64 {
	if m != nil {
		return m.Object
	}
	return 0
}

func (m *ObjectType) GetImplPos() int64 {
	if m != nil {
		return m.ImplPos
	}
	return 0
}

func (m *ObjectType) GetInterfaces() []*Ident {
	if m != nil {
		return m.Interfaces
	}
	return nil
}

func (m *ObjectType) GetFields() *FieldList {
	if m != nil {
		return m.Fields
	}
	return nil
}

// InterfaceType represents an interface type declaration.
type InterfaceType struct {
	Interface            int64      `protobuf:"varint,1,opt,name=interface,proto3" json:"interface,omitempty"`
	Fields               *FieldList `protobuf:"bytes,2,opt,name=fields,proto3" json:"fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *InterfaceType) Reset()         { *m = InterfaceType{} }
func (m *InterfaceType) String() string { return proto.CompactTextString(m) }
func (*InterfaceType) ProtoMessage()    {}
func (*InterfaceType) Descriptor() ([]byte, []int) {
	return fileDescriptor_37b5b141da493253, []int{17}
}

func (m *InterfaceType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InterfaceType.Unmarshal(m, b)
}
func (m *InterfaceType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InterfaceType.Marshal(b, m, deterministic)
}
func (m *InterfaceType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InterfaceType.Merge(m, src)
}
func (m *InterfaceType) XXX_Size() int {
	return xxx_messageInfo_InterfaceType.Size(m)
}
func (m *InterfaceType) XXX_DiscardUnknown() {
	xxx_messageInfo_InterfaceType.DiscardUnknown(m)
}

var xxx_messageInfo_InterfaceType proto.InternalMessageInfo

func (m *InterfaceType) GetInterface() int64 {
	if m != nil {
		return m.Interface
	}
	return 0
}

func (m *InterfaceType) GetFields() *FieldList {
	if m != nil {
		return m.Fields
	}
	return nil
}

// UnionType represents a union type declaration.
type UnionType struct {
	Union                int64    `protobuf:"varint,1,opt,name=union,proto3" json:"union,omitempty"`
	Members              []*Ident `protobuf:"bytes,2,rep,name=members,proto3" json:"members,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnionType) Reset()         { *m = UnionType{} }
func (m *UnionType) String() string { return proto.CompactTextString(m) }
func (*UnionType) ProtoMessage()    {}
func (*UnionType) Descriptor() ([]byte, []int) {
	return fileDescriptor_37b5b141da493253, []int{18}
}

func (m *UnionType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnionType.Unmarshal(m, b)
}
func (m *UnionType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnionType.Marshal(b, m, deterministic)
}
func (m *UnionType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnionType.Merge(m, src)
}
func (m *UnionType) XXX_Size() int {
	return xxx_messageInfo_UnionType.Size(m)
}
func (m *UnionType) XXX_DiscardUnknown() {
	xxx_messageInfo_UnionType.DiscardUnknown(m)
}

var xxx_messageInfo_UnionType proto.InternalMessageInfo

func (m *UnionType) GetUnion() int64 {
	if m != nil {
		return m.Union
	}
	return 0
}

func (m *UnionType) GetMembers() []*Ident {
	if m != nil {
		return m.Members
	}
	return nil
}

// EnumType represents an enum type declaration.
type EnumType struct {
	Enum                 int64      `protobuf:"varint,1,opt,name=enum,proto3" json:"enum,omitempty"`
	Values               *FieldList `protobuf:"bytes,2,opt,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *EnumType) Reset()         { *m = EnumType{} }
func (m *EnumType) String() string { return proto.CompactTextString(m) }
func (*EnumType) ProtoMessage()    {}
func (*EnumType) Descriptor() ([]byte, []int) {
	return fileDescriptor_37b5b141da493253, []int{19}
}

func (m *EnumType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnumType.Unmarshal(m, b)
}
func (m *EnumType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnumType.Marshal(b, m, deterministic)
}
func (m *EnumType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnumType.Merge(m, src)
}
func (m *EnumType) XXX_Size() int {
	return xxx_messageInfo_EnumType.Size(m)
}
func (m *EnumType) XXX_DiscardUnknown() {
	xxx_messageInfo_EnumType.DiscardUnknown(m)
}

var xxx_messageInfo_EnumType proto.InternalMessageInfo

func (m *EnumType) GetEnum() int64 {
	if m != nil {
		return m.Enum
	}
	return 0
}

func (m *EnumType) GetValues() *FieldList {
	if m != nil {
		return m.Values
	}
	return nil
}

// InputType represents an input type declaration.
type InputType struct {
	Input                int64      `protobuf:"varint,1,opt,name=input,proto3" json:"input,omitempty"`
	Fields               *FieldList `protobuf:"bytes,2,opt,name=fields,proto3" json:"fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *InputType) Reset()         { *m = InputType{} }
func (m *InputType) String() string { return proto.CompactTextString(m) }
func (*InputType) ProtoMessage()    {}
func (*InputType) Descriptor() ([]byte, []int) {
	return fileDescriptor_37b5b141da493253, []int{20}
}

func (m *InputType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InputType.Unmarshal(m, b)
}
func (m *InputType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InputType.Marshal(b, m, deterministic)
}
func (m *InputType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InputType.Merge(m, src)
}
func (m *InputType) XXX_Size() int {
	return xxx_messageInfo_InputType.Size(m)
}
func (m *InputType) XXX_DiscardUnknown() {
	xxx_messageInfo_InputType.DiscardUnknown(m)
}

var xxx_messageInfo_InputType proto.InternalMessageInfo

func (m *InputType) GetInput() int64 {
	if m != nil {
		return m.Input
	}
	return 0
}

func (m *InputType) GetFields() *FieldList {
	if m != nil {
		return m.Fields
	}
	return nil
}

// DirectiveType represents a directive type declaration.
type DirectiveType struct {
	Directive            int64                `protobuf:"varint,1,opt,name=directive,proto3" json:"directive,omitempty"`
	Args                 *FieldList           `protobuf:"bytes,2,opt,name=args,proto3" json:"args,omitempty"`
	OnPos                int64                `protobuf:"varint,3,opt,name=onPos,proto3" json:"onPos,omitempty"`
	Locs                 []*DirectiveLocation `protobuf:"bytes,4,rep,name=locs,proto3" json:"locs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *DirectiveType) Reset()         { *m = DirectiveType{} }
func (m *DirectiveType) String() string { return proto.CompactTextString(m) }
func (*DirectiveType) ProtoMessage()    {}
func (*DirectiveType) Descriptor() ([]byte, []int) {
	return fileDescriptor_37b5b141da493253, []int{21}
}

func (m *DirectiveType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DirectiveType.Unmarshal(m, b)
}
func (m *DirectiveType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DirectiveType.Marshal(b, m, deterministic)
}
func (m *DirectiveType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DirectiveType.Merge(m, src)
}
func (m *DirectiveType) XXX_Size() int {
	return xxx_messageInfo_DirectiveType.Size(m)
}
func (m *DirectiveType) XXX_DiscardUnknown() {
	xxx_messageInfo_DirectiveType.DiscardUnknown(m)
}

var xxx_messageInfo_DirectiveType proto.InternalMessageInfo

func (m *DirectiveType) GetDirective() int64 {
	if m != nil {
		return m.Directive
	}
	return 0
}

func (m *DirectiveType) GetArgs() *FieldList {
	if m != nil {
		return m.Args
	}
	return nil
}

func (m *DirectiveType) GetOnPos() int64 {
	if m != nil {
		return m.OnPos
	}
	return 0
}

func (m *DirectiveType) GetLocs() []*DirectiveLocation {
	if m != nil {
		return m.Locs
	}
	return nil
}

// A TypeSpec node represents a GraphQL type declaration.
type TypeSpec struct {
	Doc  *DocGroup `protobuf:"bytes,1,opt,name=doc,proto3" json:"doc,omitempty"`
	Name *Ident    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Types that are valid to be assigned to Type:
	//	*TypeSpec_Schema
	//	*TypeSpec_Scalar
	//	*TypeSpec_Object
	//	*TypeSpec_Interface
	//	*TypeSpec_Union
	//	*TypeSpec_Enum
	//	*TypeSpec_Input
	//	*TypeSpec_Directive
	Type                 isTypeSpec_Type `protobuf_oneof:"type"`
	Directives           []*DirectiveLit `protobuf:"bytes,11,rep,name=directives,proto3" json:"directives,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *TypeSpec) Reset()         { *m = TypeSpec{} }
func (m *TypeSpec) String() string { return proto.CompactTextString(m) }
func (*TypeSpec) ProtoMessage()    {}
func (*TypeSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_37b5b141da493253, []int{22}
}

func (m *TypeSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TypeSpec.Unmarshal(m, b)
}
func (m *TypeSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TypeSpec.Marshal(b, m, deterministic)
}
func (m *TypeSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TypeSpec.Merge(m, src)
}
func (m *TypeSpec) XXX_Size() int {
	return xxx_messageInfo_TypeSpec.Size(m)
}
func (m *TypeSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_TypeSpec.DiscardUnknown(m)
}

var xxx_messageInfo_TypeSpec proto.InternalMessageInfo

func (m *TypeSpec) GetDoc() *DocGroup {
	if m != nil {
		return m.Doc
	}
	return nil
}

func (m *TypeSpec) GetName() *Ident {
	if m != nil {
		return m.Name
	}
	return nil
}

type isTypeSpec_Type interface {
	isTypeSpec_Type()
}

type TypeSpec_Schema struct {
	Schema *SchemaType `protobuf:"bytes,3,opt,name=schema,proto3,oneof"`
}

type TypeSpec_Scalar struct {
	Scalar *ScalarType `protobuf:"bytes,4,opt,name=scalar,proto3,oneof"`
}

type TypeSpec_Object struct {
	Object *ObjectType `protobuf:"bytes,5,opt,name=object,proto3,oneof"`
}

type TypeSpec_Interface struct {
	Interface *InterfaceType `protobuf:"bytes,6,opt,name=interface,proto3,oneof"`
}

type TypeSpec_Union struct {
	Union *UnionType `protobuf:"bytes,7,opt,name=union,proto3,oneof"`
}

type TypeSpec_Enum struct {
	Enum *EnumType `protobuf:"bytes,8,opt,name=enum,proto3,oneof"`
}

type TypeSpec_Input struct {
	Input *InputType `protobuf:"bytes,9,opt,name=input,proto3,oneof"`
}

type TypeSpec_Directive struct {
	Directive *DirectiveType `protobuf:"bytes,10,opt,name=directive,proto3,oneof"`
}

func (*TypeSpec_Schema) isTypeSpec_Type() {}

func (*TypeSpec_Scalar) isTypeSpec_Type() {}

func (*TypeSpec_Object) isTypeSpec_Type() {}

func (*TypeSpec_Interface) isTypeSpec_Type() {}

func (*TypeSpec_Union) isTypeSpec_Type() {}

func (*TypeSpec_Enum) isTypeSpec_Type() {}

func (*TypeSpec_Input) isTypeSpec_Type() {}

func (*TypeSpec_Directive) isTypeSpec_Type() {}

func (m *TypeSpec) GetType() isTypeSpec_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *TypeSpec) GetSchema() *SchemaType {
	if x, ok := m.GetType().(*TypeSpec_Schema); ok {
		return x.Schema
	}
	return nil
}

func (m *TypeSpec) GetScalar() *ScalarType {
	if x, ok := m.GetType().(*TypeSpec_Scalar); ok {
		return x.Scalar
	}
	return nil
}

func (m *TypeSpec) GetObject() *ObjectType {
	if x, ok := m.GetType().(*TypeSpec_Object); ok {
		return x.Object
	}
	return nil
}

func (m *TypeSpec) GetInterface() *InterfaceType {
	if x, ok := m.GetType().(*TypeSpec_Interface); ok {
		return x.Interface
	}
	return nil
}

func (m *TypeSpec) GetUnion() *UnionType {
	if x, ok := m.GetType().(*TypeSpec_Union); ok {
		return x.Union
	}
	return nil
}

func (m *TypeSpec) GetEnum() *EnumType {
	if x, ok := m.GetType().(*TypeSpec_Enum); ok {
		return x.Enum
	}
	return nil
}

func (m *TypeSpec) GetInput() *InputType {
	if x, ok := m.GetType().(*TypeSpec_Input); ok {
		return x.Input
	}
	return nil
}

func (m *TypeSpec) GetDirective() *DirectiveType {
	if x, ok := m.GetType().(*TypeSpec_Directive); ok {
		return x.Directive
	}
	return nil
}

func (m *TypeSpec) GetDirectives() []*DirectiveLit {
	if m != nil {
		return m.Directives
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*TypeSpec) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*TypeSpec_Schema)(nil),
		(*TypeSpec_Scalar)(nil),
		(*TypeSpec_Object)(nil),
		(*TypeSpec_Interface)(nil),
		(*TypeSpec_Union)(nil),
		(*TypeSpec_Enum)(nil),
		(*TypeSpec_Input)(nil),
		(*TypeSpec_Directive)(nil),
	}
}

// A TypeExtensionSpec node represents a GraphQL type extension.
type TypeExtensionSpec struct {
	Doc                  *DocGroup `protobuf:"bytes,1,opt,name=doc,proto3" json:"doc,omitempty"`
	Type                 *TypeSpec `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *TypeExtensionSpec) Reset()         { *m = TypeExtensionSpec{} }
func (m *TypeExtensionSpec) String() string { return proto.CompactTextString(m) }
func (*TypeExtensionSpec) ProtoMessage()    {}
func (*TypeExtensionSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_37b5b141da493253, []int{23}
}

func (m *TypeExtensionSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TypeExtensionSpec.Unmarshal(m, b)
}
func (m *TypeExtensionSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TypeExtensionSpec.Marshal(b, m, deterministic)
}
func (m *TypeExtensionSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TypeExtensionSpec.Merge(m, src)
}
func (m *TypeExtensionSpec) XXX_Size() int {
	return xxx_messageInfo_TypeExtensionSpec.Size(m)
}
func (m *TypeExtensionSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_TypeExtensionSpec.DiscardUnknown(m)
}

var xxx_messageInfo_TypeExtensionSpec proto.InternalMessageInfo

func (m *TypeExtensionSpec) GetDoc() *DocGroup {
	if m != nil {
		return m.Doc
	}
	return nil
}

func (m *TypeExtensionSpec) GetType() *TypeSpec {
	if m != nil {
		return m.Type
	}
	return nil
}

// TypeDecl represents a general type declaration.
type TypeDecl struct {
	Doc    *DocGroup `protobuf:"bytes,1,opt,name=doc,proto3" json:"doc,omitempty"`
	TokPos int64     `protobuf:"varint,2,opt,name=tokPos,proto3" json:"tokPos,omitempty"`
	Tok    int64     `protobuf:"varint,3,opt,name=tok,proto3" json:"tok,omitempty"`
	// Types that are valid to be assigned to Spec:
	//	*TypeDecl_TypeSpec
	//	*TypeDecl_TypeExtSpec
	Spec                 isTypeDecl_Spec `protobuf_oneof:"spec"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *TypeDecl) Reset()         { *m = TypeDecl{} }
func (m *TypeDecl) String() string { return proto.CompactTextString(m) }
func (*TypeDecl) ProtoMessage()    {}
func (*TypeDecl) Descriptor() ([]byte, []int) {
	return fileDescriptor_37b5b141da493253, []int{24}
}

func (m *TypeDecl) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TypeDecl.Unmarshal(m, b)
}
func (m *TypeDecl) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TypeDecl.Marshal(b, m, deterministic)
}
func (m *TypeDecl) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TypeDecl.Merge(m, src)
}
func (m *TypeDecl) XXX_Size() int {
	return xxx_messageInfo_TypeDecl.Size(m)
}
func (m *TypeDecl) XXX_DiscardUnknown() {
	xxx_messageInfo_TypeDecl.DiscardUnknown(m)
}

var xxx_messageInfo_TypeDecl proto.InternalMessageInfo

func (m *TypeDecl) GetDoc() *DocGroup {
	if m != nil {
		return m.Doc
	}
	return nil
}

func (m *TypeDecl) GetTokPos() int64 {
	if m != nil {
		return m.TokPos
	}
	return 0
}

func (m *TypeDecl) GetTok() int64 {
	if m != nil {
		return m.Tok
	}
	return 0
}

type isTypeDecl_Spec interface {
	isTypeDecl_Spec()
}

type TypeDecl_TypeSpec struct {
	TypeSpec *TypeSpec `protobuf:"bytes,4,opt,name=typeSpec,proto3,oneof"`
}

type TypeDecl_TypeExtSpec struct {
	TypeExtSpec *TypeExtensionSpec `protobuf:"bytes,5,opt,name=typeExtSpec,proto3,oneof"`
}

func (*TypeDecl_TypeSpec) isTypeDecl_Spec() {}

func (*TypeDecl_TypeExtSpec) isTypeDecl_Spec() {}

func (m *TypeDecl) GetSpec() isTypeDecl_Spec {
	if m != nil {
		return m.Spec
	}
	return nil
}

func (m *TypeDecl) GetTypeSpec() *TypeSpec {
	if x, ok := m.GetSpec().(*TypeDecl_TypeSpec); ok {
		return x.TypeSpec
	}
	return nil
}

func (m *TypeDecl) GetTypeExtSpec() *TypeExtensionSpec {
	if x, ok := m.GetSpec().(*TypeDecl_TypeExtSpec); ok {
		return x.TypeExtSpec
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*TypeDecl) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*TypeDecl_TypeSpec)(nil),
		(*TypeDecl_TypeExtSpec)(nil),
	}
}

func init() {
	proto.RegisterEnum("DirectiveLocation_Loc", DirectiveLocation_Loc_name, DirectiveLocation_Loc_value)
	proto.RegisterType((*Document)(nil), "Document")
	proto.RegisterType((*DocGroup)(nil), "DocGroup")
	proto.RegisterType((*DocGroup_Doc)(nil), "DocGroup.Doc")
	proto.RegisterType((*Arg)(nil), "Arg")
	proto.RegisterType((*Field)(nil), "Field")
	proto.RegisterType((*FieldList)(nil), "FieldList")
	proto.RegisterType((*Ident)(nil), "Ident")
	proto.RegisterType((*BasicLit)(nil), "BasicLit")
	proto.RegisterType((*ListLit)(nil), "ListLit")
	proto.RegisterType((*ObjLit)(nil), "ObjLit")
	proto.RegisterType((*List)(nil), "List")
	proto.RegisterType((*NonNull)(nil), "NonNull")
	proto.RegisterType((*DirectiveLit)(nil), "DirectiveLit")
	proto.RegisterType((*DirectiveLocation)(nil), "DirectiveLocation")
	proto.RegisterType((*CallExpr)(nil), "CallExpr")
	proto.RegisterType((*SchemaType)(nil), "SchemaType")
	proto.RegisterType((*ScalarType)(nil), "ScalarType")
	proto.RegisterType((*ObjectType)(nil), "ObjectType")
	proto.RegisterType((*InterfaceType)(nil), "InterfaceType")
	proto.RegisterType((*UnionType)(nil), "UnionType")
	proto.RegisterType((*EnumType)(nil), "EnumType")
	proto.RegisterType((*InputType)(nil), "InputType")
	proto.RegisterType((*DirectiveType)(nil), "DirectiveType")
	proto.RegisterType((*TypeSpec)(nil), "TypeSpec")
	proto.RegisterType((*TypeExtensionSpec)(nil), "TypeExtensionSpec")
	proto.RegisterType((*TypeDecl)(nil), "TypeDecl")
}

func init() { proto.RegisterFile("ast.proto", fileDescriptor_37b5b141da493253) }

var fileDescriptor_37b5b141da493253 = []byte{
	// 1348 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x57, 0xcb, 0x6e, 0xdb, 0x46,
	0x14, 0x15, 0x45, 0x52, 0x22, 0xaf, 0x6c, 0x87, 0x99, 0x18, 0xae, 0xe0, 0x34, 0x89, 0x43, 0x24,
	0xa9, 0x37, 0xe5, 0xc2, 0x45, 0xbb, 0xae, 0x1e, 0xb4, 0xa5, 0x40, 0xa6, 0x1c, 0x5a, 0x4a, 0x81,
	0x76, 0x61, 0xd0, 0x34, 0xe3, 0x30, 0xa1, 0x38, 0x2a, 0x39, 0x0a, 0x92, 0x5f, 0x68, 0xff, 0xa5,
	0xeb, 0xa2, 0xfd, 0x9e, 0xfe, 0x47, 0x71, 0xe7, 0x41, 0xd1, 0x8f, 0x3c, 0xd0, 0xae, 0x34, 0xf7,
	0x31, 0x67, 0xee, 0x9c, 0x7b, 0x66, 0x86, 0x02, 0x3b, 0x2a, 0x99, 0xb7, 0x2c, 0x28, 0xa3, 0xee,
	0x1f, 0x1a, 0x58, 0x43, 0x1a, 0xaf, 0x16, 0x49, 0xce, 0x08, 0x01, 0x23, 0x8f, 0x16, 0x49, 0x57,
	0xdb, 0xd3, 0xf6, 0xed, 0x90, 0x8f, 0xc9, 0x7d, 0xd0, 0x2f, 0x68, 0xdc, 0x6d, 0xee, 0x69, 0xfb,
	0x9d, 0x03, 0xdb, 0x1b, 0xd2, 0xf8, 0xa8, 0xa0, 0xab, 0x65, 0x88, 0x5e, 0xf2, 0x2d, 0xc0, 0x45,
	0x5a, 0x24, 0x31, 0x4b, 0xdf, 0x25, 0x65, 0x57, 0xdf, 0xd3, 0xf7, 0x3b, 0x07, 0x9b, 0xde, 0x50,
	0xb9, 0x26, 0x29, 0x0b, 0x6b, 0x09, 0xe4, 0x31, 0xb4, 0xca, 0xf8, 0x75, 0xb2, 0x88, 0xba, 0x86,
	0x84, 0x9b, 0x7d, 0x58, 0x26, 0xc3, 0x24, 0xce, 0x42, 0x19, 0x20, 0x8f, 0xc0, 0x64, 0x1f, 0x96,
	0x49, 0xd9, 0x35, 0x39, 0x58, 0x2d, 0x43, 0xf8, 0xdd, 0x77, 0xbc, 0x5e, 0x5e, 0x03, 0x79, 0x0c,
	0x46, 0x96, 0x96, 0xac, 0xab, 0xa9, 0x85, 0x65, 0x00, 0x07, 0x21, 0x0f, 0xed, 0x1e, 0x81, 0x3e,
	0xa4, 0x31, 0xee, 0x8c, 0x25, 0xef, 0x99, 0xda, 0x19, 0x8e, 0xd1, 0x17, 0xbf, 0x8e, 0x0a, 0xbe,
	0x35, 0x3d, 0xe4, 0x63, 0xd2, 0x85, 0x76, 0x4c, 0x17, 0x48, 0x46, 0x57, 0xdf, 0xd3, 0xf6, 0xad,
	0x50, 0x99, 0xee, 0x6f, 0x1a, 0xe8, 0xbd, 0xe2, 0x92, 0xec, 0xd6, 0x38, 0xea, 0x1c, 0xb4, 0xbc,
	0xf1, 0x45, 0x92, 0x33, 0xc9, 0xd5, 0x23, 0x30, 0xce, 0xb3, 0x94, 0x55, 0x64, 0xf5, 0xa3, 0x32,
	0x8d, 0x27, 0x29, 0x1b, 0x35, 0x42, 0x1e, 0x20, 0x0f, 0xc1, 0xc8, 0x30, 0x41, 0xe7, 0x09, 0x96,
	0x37, 0x49, 0x4b, 0x26, 0xe3, 0xe8, 0x27, 0x0f, 0xc0, 0xa0, 0x18, 0x17, 0xf4, 0xb4, 0xbd, 0xe9,
	0xf9, 0x1b, 0x19, 0x46, 0x77, 0xbf, 0x0d, 0xe6, 0xbb, 0x28, 0x5b, 0x25, 0xee, 0x3f, 0x4d, 0x30,
	0x0f, 0xd3, 0x24, 0xbb, 0x50, 0xed, 0xd1, 0x6e, 0x6d, 0x8f, 0xaa, 0xb5, 0x79, 0x4b, 0xad, 0x0f,
	0xc1, 0x88, 0x8a, 0xcb, 0x52, 0x96, 0x02, 0x1e, 0x87, 0xc3, 0x7a, 0x42, 0xee, 0x27, 0x0f, 0xc1,
	0x4c, 0x31, 0x5d, 0xd6, 0x22, 0x27, 0x8f, 0x1a, 0xa1, 0x70, 0x93, 0xfb, 0x92, 0x7b, 0x93, 0x87,
	0x4d, 0xbe, 0x15, 0xbe, 0x8f, 0xb4, 0x64, 0xe4, 0x09, 0xb4, 0x73, 0x9a, 0x07, 0xab, 0x2c, 0xeb,
	0xb6, 0xe4, 0x56, 0x03, 0x61, 0x8f, 0x1a, 0xa1, 0x0a, 0x55, 0x74, 0xb5, 0xaf, 0xd3, 0xa5, 0x5d,
	0xa3, 0xcb, 0xba, 0x46, 0x97, 0x76, 0x8d, 0x2e, 0xfb, 0x2a, 0x5d, 0x9a, 0xa0, 0xeb, 0x9a, 0x3a,
	0xe1, 0x33, 0xea, 0xec, 0xb7, 0xc0, 0x40, 0x89, 0xf5, 0x6d, 0x68, 0x5f, 0x24, 0xaf, 0xa2, 0x55,
	0xc6, 0xdc, 0x5f, 0xc0, 0xae, 0x78, 0x41, 0x6d, 0xd0, 0x65, 0x92, 0xa7, 0xf9, 0x25, 0xa7, 0x5b,
	0x0f, 0x95, 0x89, 0x3c, 0x73, 0x2e, 0x9a, 0x7c, 0x89, 0x96, 0xe0, 0x52, 0x52, 0x81, 0x8a, 0xca,
	0x68, 0x89, 0xb3, 0x74, 0x31, 0x4b, 0x9a, 0xee, 0xf7, 0x60, 0x72, 0x4e, 0x31, 0x05, 0x5b, 0x72,
	0x42, 0x4b, 0x05, 0x2c, 0xcd, 0xea, 0x40, 0x36, 0xd7, 0x07, 0xd2, 0x3d, 0x01, 0x4b, 0x11, 0x45,
	0x76, 0xc1, 0xe2, 0x82, 0x58, 0x4f, 0xad, 0x6c, 0x9c, 0xfb, 0x36, 0xcd, 0x2f, 0x94, 0xbc, 0x71,
	0x4c, 0xb6, 0xa5, 0x80, 0x78, 0x29, 0x76, 0x28, 0xd5, 0x64, 0x43, 0x5b, 0x32, 0xeb, 0x5a, 0xd0,
	0x12, 0x24, 0xba, 0xbf, 0x82, 0xc1, 0x77, 0x5d, 0xe9, 0x40, 0xfb, 0xb4, 0x0e, 0x9a, 0x9f, 0xd1,
	0x81, 0xfe, 0x51, 0x1d, 0x28, 0xe2, 0xdd, 0x00, 0xda, 0x32, 0xfa, 0xbf, 0x56, 0xad, 0xf0, 0x7e,
	0x82, 0x8d, 0x7a, 0xb3, 0x71, 0xf7, 0x11, 0x5b, 0x53, 0x25, 0x8c, 0xdb, 0x38, 0x46, 0x61, 0xd5,
	0x0e, 0x87, 0xed, 0x0d, 0xa2, 0x2c, 0xf3, 0xdf, 0x2f, 0x0b, 0x71, 0x36, 0xdc, 0xbf, 0x75, 0xb8,
	0xbb, 0x46, 0xa6, 0x71, 0xc4, 0x52, 0x9a, 0x23, 0x7c, 0xc9, 0xa2, 0x82, 0x29, 0x78, 0x6e, 0x90,
	0x7d, 0xd0, 0x33, 0x79, 0x7f, 0x6e, 0x1d, 0xec, 0x78, 0x37, 0xa6, 0x79, 0x13, 0x1a, 0x87, 0x98,
	0x82, 0x87, 0x5a, 0x9f, 0xd0, 0x98, 0xd8, 0x60, 0x06, 0xf4, 0x84, 0x96, 0x4e, 0x03, 0x87, 0x2f,
	0x56, 0x49, 0xf1, 0xc1, 0xd1, 0xc8, 0x06, 0x58, 0xc7, 0xf3, 0x59, 0x6f, 0x36, 0x9e, 0x06, 0x4e,
	0x93, 0x38, 0xb0, 0x71, 0x3a, 0xef, 0x9f, 0x0e, 0xc2, 0xf1, 0x09, 0xf7, 0xe8, 0x98, 0x7a, 0x38,
	0xf6, 0x27, 0x43, 0xc7, 0x20, 0x5f, 0xc1, 0xbd, 0xc3, 0xb0, 0x77, 0x74, 0xec, 0x07, 0xb3, 0xb3,
	0xa1, 0x7f, 0x38, 0x0e, 0xc6, 0x3c, 0xc7, 0x24, 0xf7, 0xe0, 0x4e, 0x15, 0x38, 0x3d, 0x09, 0xfd,
	0xde, 0xd0, 0x69, 0xa1, 0x73, 0x1c, 0x4c, 0xc6, 0x81, 0x7f, 0xa6, 0x62, 0x4e, 0x1b, 0x21, 0x5e,
	0xf6, 0xc2, 0x71, 0xaf, 0x3f, 0xf1, 0xeb, 0x10, 0x16, 0x96, 0x31, 0x9c, 0x0e, 0xe6, 0x3c, 0xcd,
	0x26, 0x00, 0xad, 0xd3, 0xc1, 0xc8, 0x3f, 0xee, 0x39, 0x20, 0xc6, 0xbd, 0x49, 0x2f, 0x74, 0x3a,
	0x38, 0x9e, 0xf6, 0x9f, 0xfb, 0x83, 0x99, 0xb3, 0x41, 0xb6, 0xc1, 0xe1, 0x85, 0xd5, 0x71, 0x36,
	0x71, 0x81, 0x5e, 0x78, 0x34, 0xbf, 0x5e, 0xe3, 0x16, 0xd9, 0x04, 0x7b, 0x1c, 0xcc, 0xfc, 0xf0,
	0xb0, 0x37, 0xf0, 0x9d, 0x3b, 0xb8, 0xad, 0x79, 0x80, 0x11, 0x87, 0x58, 0x60, 0xf8, 0xc1, 0xfc,
	0xd8, 0xb9, 0x4b, 0xb6, 0x00, 0x70, 0x74, 0xf6, 0xb2, 0x37, 0x99, 0xfb, 0x0e, 0x41, 0x36, 0xc6,
	0xc1, 0xc9, 0x7c, 0x76, 0x26, 0x17, 0xbd, 0x47, 0x76, 0x61, 0x47, 0x78, 0x6e, 0x2c, 0xbd, 0xed,
	0xce, 0xc0, 0x52, 0xfd, 0x24, 0x3b, 0xd0, 0xca, 0x96, 0x51, 0x91, 0xe4, 0xb2, 0x69, 0xd2, 0x22,
	0x5d, 0x29, 0x00, 0x71, 0xa2, 0x0d, 0xaf, 0x57, 0x5c, 0xca, 0x7b, 0x71, 0x07, 0x5a, 0x85, 0x98,
	0x21, 0x8e, 0xb3, 0xb4, 0xdc, 0xe7, 0x00, 0xa7, 0xfc, 0x09, 0xc3, 0x07, 0x0b, 0xb3, 0xe4, 0x4b,
	0x27, 0x71, 0xe5, 0xf3, 0xf6, 0x04, 0xda, 0x05, 0xa5, 0x6c, 0xba, 0x2c, 0xa5, 0x74, 0xeb, 0x17,
	0xaf, 0x0a, 0xb9, 0x3f, 0x22, 0x56, 0x94, 0x45, 0xc5, 0x1a, 0x0b, 0xad, 0x35, 0x16, 0x5a, 0x9f,
	0xba, 0xdd, 0xf1, 0xb5, 0x82, 0xe9, 0xf9, 0x9b, 0x24, 0x66, 0x0a, 0x82, 0x72, 0x4b, 0x41, 0x08,
	0x0b, 0x6f, 0x9e, 0x74, 0xb1, 0xcc, 0xf0, 0x4c, 0x88, 0x6b, 0x42, 0x99, 0xe4, 0x19, 0x40, 0x9a,
	0xb3, 0xa4, 0x78, 0x15, 0xc5, 0xd5, 0xcb, 0xae, 0x96, 0xa8, 0x45, 0x88, 0x0b, 0xad, 0x57, 0xb8,
	0x81, 0x52, 0xbe, 0x13, 0xf5, 0xfd, 0xc8, 0x88, 0xfb, 0x02, 0x36, 0xc7, 0x6a, 0x06, 0x2f, 0xe7,
	0x6b, 0xb0, 0x2b, 0x08, 0x59, 0xd1, 0xda, 0x51, 0x83, 0x6c, 0x7e, 0x14, 0x72, 0x00, 0xf6, 0x3c,
	0x4f, 0x69, 0xce, 0xe1, 0xb6, 0xc1, 0x5c, 0xa1, 0xa1, 0x0e, 0x1e, 0x37, 0xc8, 0x1e, 0xb4, 0x17,
	0xc9, 0xe2, 0x3c, 0x29, 0xca, 0xea, 0x5e, 0x16, 0xe5, 0x2b, 0xb7, 0xdb, 0x07, 0xcb, 0xcf, 0x57,
	0x0b, 0x8e, 0x41, 0xc0, 0x48, 0xf2, 0xd5, 0x42, 0x42, 0xf0, 0x31, 0x16, 0xc2, 0x2f, 0xc8, 0x5b,
	0x0b, 0x11, 0x11, 0xd7, 0x07, 0x7b, 0x9c, 0x2f, 0x57, 0x4c, 0x15, 0x92, 0xa2, 0xa1, 0x0a, 0xe1,
	0xc6, 0x17, 0xed, 0xe7, 0x77, 0x0d, 0x36, 0xab, 0xab, 0x41, 0x71, 0x54, 0xbd, 0x4d, 0x8a, 0xa3,
	0xca, 0x51, 0xbd, 0xde, 0xcd, 0x8f, 0xbc, 0xde, 0xdb, 0x60, 0xd2, 0x1c, 0xdb, 0x2a, 0x44, 0x2a,
	0x0c, 0xf2, 0x0c, 0x8c, 0x8c, 0xc6, 0xd8, 0x2a, 0xe4, 0x83, 0xdc, 0xbc, 0x8c, 0x42, 0x1e, 0x77,
	0xff, 0xd4, 0xc1, 0xc2, 0x22, 0x4e, 0x97, 0x49, 0xfc, 0xdf, 0xbf, 0x30, 0x9e, 0x56, 0x67, 0x40,
	0x5c, 0xa3, 0x1d, 0x6f, 0x7d, 0x40, 0x46, 0x8d, 0xea, 0x48, 0x3c, 0xad, 0xe4, 0x6d, 0x54, 0x69,
	0x4a, 0xfb, 0x22, 0x8d, 0xab, 0xfd, 0x69, 0x25, 0x61, 0x53, 0xa6, 0xad, 0xf5, 0x8d, 0x69, 0x52,
	0xd1, 0x5e, 0x5d, 0x5a, 0xe2, 0xdb, 0x63, 0xcb, 0xbb, 0xa2, 0xbe, 0x51, 0xe3, 0xaa, 0xd8, 0xa4,
	0x76, 0xda, 0x92, 0xc9, 0x4a, 0x56, 0xf8, 0xd8, 0x08, 0x25, 0x3d, 0x92, 0xda, 0xb0, 0x24, 0x05,
	0x4a, 0x34, 0xf8, 0xe0, 0x48, 0xa1, 0xc8, 0xbe, 0xdb, 0x12, 0xa4, 0x92, 0x04, 0x7f, 0xb1, 0xb8,
	0x0a, 0xbc, 0x7a, 0x3f, 0x41, 0x16, 0x76, 0xa5, 0xe5, 0x58, 0xd8, 0xba, 0xc3, 0x57, 0x3f, 0x5e,
	0x3a, 0x5f, 0xf8, 0xf1, 0xe2, 0x4e, 0xe1, 0x2e, 0x62, 0xf9, 0xef, 0x59, 0x92, 0x97, 0x29, 0xcd,
	0x3f, 0xdf, 0xc2, 0x07, 0x62, 0x66, 0xf5, 0xd1, 0xaa, 0x1a, 0x1f, 0x0a, 0xc0, 0xbf, 0x34, 0xa1,
	0x05, 0xfc, 0x06, 0xff, 0x34, 0xd0, 0x0e, 0xb4, 0x18, 0x7d, 0xbb, 0xbe, 0x4b, 0xa4, 0x45, 0x1c,
	0xd0, 0x19, 0x7d, 0x2b, 0x95, 0x88, 0x43, 0xf2, 0x0d, 0x58, 0x4c, 0xae, 0x72, 0xe5, 0x9f, 0x00,
	0x3a, 0x46, 0x8d, 0xb0, 0x0a, 0x92, 0x1f, 0xa0, 0xc3, 0xc4, 0x6e, 0x78, 0xae, 0xe8, 0x3c, 0xf1,
	0x6e, 0xec, 0x70, 0xd4, 0x08, 0xeb, 0x89, 0xc8, 0x46, 0x89, 0xbf, 0xe6, 0xcf, 0x7a, 0x54, 0xb2,
	0xf3, 0x16, 0xff, 0xaf, 0xf3, 0xdd, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xa3, 0xc5, 0x26, 0xd5,
	0xf8, 0x0c, 0x00, 0x00,
}
